// Generated by dedot cli

import type {
  ConstructorTxOptions,
  GenericConstructorTx,
  GenericConstructorTxCall,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
  SolGenericContractApi,
} from 'dedot/contracts';

export interface ConstructorTx<
  ContractApi extends SolGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<Type> {
  /**
   * @param {ConstructorTxOptions} options
   **/
  new: GenericConstructorTxCall<
    (options?: ConstructorTxOptions) => GenericInstantiateSubmittableExtrinsic<ContractApi>,
    Type
  >;
}
