// Generated by dedot cli

import type { BytesLike, H160 } from 'dedot/codecs';
import type { GenericContractEvent, GenericContractEvents, MetadataType } from 'dedot/contracts';

export interface ContractEvents<Type extends MetadataType> extends GenericContractEvents<Type> {
  FallbackCalled: GenericContractEvent<
    'FallbackCalled',
    [
      /**
       * @indexed: true
       **/
      H160,
      /**
       * @indexed: false
       **/
      bigint,
      /**
       * @indexed: false
       **/
      BytesLike,
    ],
    Type
  >;

  Received: GenericContractEvent<
    'Received',
    {
      /**
       * @indexed: true
       **/
      sender: H160;
      /**
       * @indexed: false
       **/
      value: bigint;
    },
    Type
  >;
}
