// Generated by dedot cli

import type { SolGenericContractEvents } from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';

export interface ContractEvents<ChainApi extends GenericSubstrateApi> extends SolGenericContractEvents<ChainApi> {}
