// Generated by @delightfuldot/codegen

import type { GenericChainStorage, GenericStorageQuery, Callback } from '@delightfuldot/types';
import type {
  AccountId20Like,
  H256,
  Bytes,
  Digest,
  Phase,
  FixedU128,
  Perbill,
  AccountId20,
  Percent,
  Data,
  BytesLike,
  FixedBytes,
  H160,
  U256,
} from '@delightfuldot/codecs';
import type {
  FrameSystemAccountInfo,
  FrameSupportDispatchPerDispatchClass,
  FrameSystemEventRecord,
  FrameSystemLastRuntimeUpgradeInfo,
  CumulusPalletParachainSystemUnincludedSegmentAncestor,
  CumulusPalletParachainSystemUnincludedSegmentSegmentTracker,
  PolkadotPrimitivesV6PersistedValidationData,
  PolkadotPrimitivesV6UpgradeRestriction,
  PolkadotPrimitivesV6UpgradeGoAhead,
  SpTrieStorageProof,
  CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot,
  PolkadotPrimitivesV6AbridgedHostConfiguration,
  CumulusPrimitivesParachainInherentMessageQueueChain,
  PolkadotParachainPrimitivesPrimitivesId,
  PolkadotCorePrimitivesOutboundHrmpMessage,
  SpWeightsWeightV2Weight,
  CumulusPalletParachainSystemCodeUpgradeAuthorization,
  PalletBalancesAccountData,
  PalletBalancesBalanceLock,
  PalletBalancesReserveData,
  PalletBalancesIdAmount,
  PalletBalancesIdAmount002,
  PalletTransactionPaymentReleases,
  PalletParachainStakingParachainBondConfig,
  PalletParachainStakingRoundInfo,
  PalletParachainStakingDelegator,
  PalletParachainStakingCandidateMetadata,
  PalletParachainStakingDelegationRequestsScheduledRequest,
  PalletParachainStakingAutoCompoundAutoCompoundConfig,
  PalletParachainStakingDelegations,
  PalletParachainStakingSetBoundedOrderedSet,
  PalletParachainStakingCollatorSnapshot,
  PalletParachainStakingDelayedPayout,
  PalletParachainStakingInflationInflationInfo,
  PalletAuthorSlotFilterNumNonZeroU32,
  PalletAuthorMappingRegistrationInfo,
  NimbusPrimitivesNimbusCryptoPublic,
  PalletMoonbeamOrbitersCollatorPoolInfo,
  PalletProxyProxyDefinition,
  PalletProxyAnnouncement,
  PalletIdentityRegistration,
  PalletIdentityRegistrarInfo,
  PalletMultisigMultisig,
  PalletEvmCodeMetadata,
  EthereumTransactionTransactionV2,
  FpRpcTransactionStatus,
  EthereumReceiptReceiptV3,
  EthereumBlock,
  PalletSchedulerScheduled,
  FrameSupportPreimagesBounded,
  PalletDemocracyReferendumInfo,
  PalletDemocracyVoteVoting,
  PalletDemocracyVoteThreshold,
  PalletDemocracyMetadataOwner,
  PalletPreimageOldRequestStatus,
  PalletPreimageRequestStatus,
  PalletConvictionVotingVoteVoting,
  PalletReferendaReferendumInfo,
  MoonbeamRuntimeRuntimeCall,
  PalletCollectiveVotes,
  PalletTreasuryProposal,
  PalletTreasurySpendStatus,
  PalletCrowdloanRewardsRewardInfo,
  CumulusPalletXcmpQueueInboundChannelDetails,
  CumulusPalletXcmpQueueOutboundChannelDetails,
  CumulusPalletXcmpQueueQueueConfigData,
  CumulusPalletDmpQueueConfigData,
  CumulusPalletDmpQueuePageIndexData,
  PalletXcmQueryStatus,
  XcmVersionedMultiLocation,
  PalletXcmVersionMigrationStage,
  PalletXcmRemoteLockedFungibleRecord,
  XcmVersionedAssetId,
  PalletAssetsAssetDetails,
  PalletAssetsAssetAccount,
  PalletAssetsApproval,
  PalletAssetsAssetMetadata,
  MoonbeamRuntimeXcmConfigAssetType,
  PalletAssetManagerAssetInfo,
  PalletXcmTransactorRemoteTransactInfoWithMaxWeight,
  StagingXcmV3MultilocationMultiLocation,
  PalletXcmTransactorRelayIndicesRelayChainIndices,
  PalletRandomnessRequestState,
  PalletRandomnessRandomnessResult,
  PalletRandomnessRequestType,
} from './types';

export interface ChainStorage extends GenericChainStorage {
  /**
   * Pallet `System`'s storage queries
   **/
  system: {
    /**
     * The full account information for a particular account ID.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<FrameSystemAccountInfo>=} callback
     **/
    account: GenericStorageQuery<(arg: AccountId20Like) => FrameSystemAccountInfo>;

    /**
     * Total extrinsics count for the current block.
     *
     * @param {Callback<number | undefined>=} callback
     **/
    extrinsicCount: GenericStorageQuery<() => number | undefined>;

    /**
     * The current weight for the block.
     *
     * @param {Callback<FrameSupportDispatchPerDispatchClass>=} callback
     **/
    blockWeight: GenericStorageQuery<() => FrameSupportDispatchPerDispatchClass>;

    /**
     * Total length (in bytes) for all extrinsics put together, for the current block.
     *
     * @param {Callback<number | undefined>=} callback
     **/
    allExtrinsicsLen: GenericStorageQuery<() => number | undefined>;

    /**
     * Map of block numbers to block hashes.
     *
     * @param {number} arg
     * @param {Callback<H256>=} callback
     **/
    blockHash: GenericStorageQuery<(arg: number) => H256>;

    /**
     * Extrinsics data for the current block (maps an extrinsic's index to its data).
     *
     * @param {number} arg
     * @param {Callback<Bytes>=} callback
     **/
    extrinsicData: GenericStorageQuery<(arg: number) => Bytes>;

    /**
     * The current block number being processed. Set by `execute_block`.
     *
     * @param {Callback<number>=} callback
     **/
    number: GenericStorageQuery<() => number>;

    /**
     * Hash of the previous block.
     *
     * @param {Callback<H256>=} callback
     **/
    parentHash: GenericStorageQuery<() => H256>;

    /**
     * Digest of the current block, also part of the block header.
     *
     * @param {Callback<Digest>=} callback
     **/
    digest: GenericStorageQuery<() => Digest>;

    /**
     * Events deposited for the current block.
     *
     * NOTE: The item is unbound and should therefore never be read on chain.
     * It could otherwise inflate the PoV size of a block.
     *
     * Events have a large in-memory size. Box the events to not go out-of-memory
     * just in case someone still reads them from within the runtime.
     *
     * @param {Callback<Array<FrameSystemEventRecord>>=} callback
     **/
    events: GenericStorageQuery<() => Array<FrameSystemEventRecord>>;

    /**
     * The number of events in the `Events<T>` list.
     *
     * @param {Callback<number>=} callback
     **/
    eventCount: GenericStorageQuery<() => number>;

    /**
     * Mapping between a topic (represented by T::Hash) and a vector of indexes
     * of events in the `<Events<T>>` list.
     *
     * All topic vectors have deterministic storage locations depending on the topic. This
     * allows light-clients to leverage the changes trie storage tracking mechanism and
     * in case of changes fetch the list of events of interest.
     *
     * The value has the type `(BlockNumberFor<T>, EventIndex)` because if we used only just
     * the `EventIndex` then in case if the topic has the same contents on the next block
     * no notification will be triggered thus the event might be lost.
     *
     * @param {H256} arg
     * @param {Callback<Array<[number, number]>>=} callback
     **/
    eventTopics: GenericStorageQuery<(arg: H256) => Array<[number, number]>>;

    /**
     * Stores the `spec_version` and `spec_name` of when the last runtime upgrade happened.
     *
     * @param {Callback<FrameSystemLastRuntimeUpgradeInfo | undefined>=} callback
     **/
    lastRuntimeUpgrade: GenericStorageQuery<() => FrameSystemLastRuntimeUpgradeInfo | undefined>;

    /**
     * True if we have upgraded so that `type RefCount` is `u32`. False (default) if not.
     *
     * @param {Callback<boolean>=} callback
     **/
    upgradedToU32RefCount: GenericStorageQuery<() => boolean>;

    /**
     * True if we have upgraded so that AccountInfo contains three types of `RefCount`. False
     * (default) if not.
     *
     * @param {Callback<boolean>=} callback
     **/
    upgradedToTripleRefCount: GenericStorageQuery<() => boolean>;

    /**
     * The execution phase of the block.
     *
     * @param {Callback<Phase | undefined>=} callback
     **/
    executionPhase: GenericStorageQuery<() => Phase | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ParachainSystem`'s storage queries
   **/
  parachainSystem: {
    /**
     * Latest included block descendants the runtime accepted. In other words, these are
     * ancestors of the currently executing block which have not been included in the observed
     * relay-chain state.
     *
     * The segment length is limited by the capacity returned from the [`ConsensusHook`] configured
     * in the pallet.
     *
     * @param {Callback<Array<CumulusPalletParachainSystemUnincludedSegmentAncestor>>=} callback
     **/
    unincludedSegment: GenericStorageQuery<() => Array<CumulusPalletParachainSystemUnincludedSegmentAncestor>>;

    /**
     * Storage field that keeps track of bandwidth used by the unincluded segment along with the
     * latest HRMP watermark. Used for limiting the acceptance of new blocks with
     * respect to relay chain constraints.
     *
     * @param {Callback<CumulusPalletParachainSystemUnincludedSegmentSegmentTracker | undefined>=} callback
     **/
    aggregatedUnincludedSegment: GenericStorageQuery<
      () => CumulusPalletParachainSystemUnincludedSegmentSegmentTracker | undefined
    >;

    /**
     * In case of a scheduled upgrade, this storage field contains the validation code to be
     * applied.
     *
     * As soon as the relay chain gives us the go-ahead signal, we will overwrite the
     * [`:code`][sp_core::storage::well_known_keys::CODE] which will result the next block process
     * with the new validation code. This concludes the upgrade process.
     *
     * @param {Callback<Bytes>=} callback
     **/
    pendingValidationCode: GenericStorageQuery<() => Bytes>;

    /**
     * Validation code that is set by the parachain and is to be communicated to collator and
     * consequently the relay-chain.
     *
     * This will be cleared in `on_initialize` of each new block if no other pallet already set
     * the value.
     *
     * @param {Callback<Bytes | undefined>=} callback
     **/
    newValidationCode: GenericStorageQuery<() => Bytes | undefined>;

    /**
     * The [`PersistedValidationData`] set for this block.
     * This value is expected to be set only once per block and it's never stored
     * in the trie.
     *
     * @param {Callback<PolkadotPrimitivesV6PersistedValidationData | undefined>=} callback
     **/
    validationData: GenericStorageQuery<() => PolkadotPrimitivesV6PersistedValidationData | undefined>;

    /**
     * Were the validation data set to notify the relay chain?
     *
     * @param {Callback<boolean>=} callback
     **/
    didSetValidationCode: GenericStorageQuery<() => boolean>;

    /**
     * The relay chain block number associated with the last parachain block.
     *
     * This is updated in `on_finalize`.
     *
     * @param {Callback<number>=} callback
     **/
    lastRelayChainBlockNumber: GenericStorageQuery<() => number>;

    /**
     * An option which indicates if the relay-chain restricts signalling a validation code upgrade.
     * In other words, if this is `Some` and [`NewValidationCode`] is `Some` then the produced
     * candidate will be invalid.
     *
     * This storage item is a mirror of the corresponding value for the current parachain from the
     * relay-chain. This value is ephemeral which means it doesn't hit the storage. This value is
     * set after the inherent.
     *
     * @param {Callback<PolkadotPrimitivesV6UpgradeRestriction | undefined>=} callback
     **/
    upgradeRestrictionSignal: GenericStorageQuery<() => PolkadotPrimitivesV6UpgradeRestriction | undefined>;

    /**
     * Optional upgrade go-ahead signal from the relay-chain.
     *
     * This storage item is a mirror of the corresponding value for the current parachain from the
     * relay-chain. This value is ephemeral which means it doesn't hit the storage. This value is
     * set after the inherent.
     *
     * @param {Callback<PolkadotPrimitivesV6UpgradeGoAhead | undefined>=} callback
     **/
    upgradeGoAhead: GenericStorageQuery<() => PolkadotPrimitivesV6UpgradeGoAhead | undefined>;

    /**
     * The state proof for the last relay parent block.
     *
     * This field is meant to be updated each block with the validation data inherent. Therefore,
     * before processing of the inherent, e.g. in `on_initialize` this data may be stale.
     *
     * This data is also absent from the genesis.
     *
     * @param {Callback<SpTrieStorageProof | undefined>=} callback
     **/
    relayStateProof: GenericStorageQuery<() => SpTrieStorageProof | undefined>;

    /**
     * The snapshot of some state related to messaging relevant to the current parachain as per
     * the relay parent.
     *
     * This field is meant to be updated each block with the validation data inherent. Therefore,
     * before processing of the inherent, e.g. in `on_initialize` this data may be stale.
     *
     * This data is also absent from the genesis.
     *
     * @param {Callback<CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot | undefined>=} callback
     **/
    relevantMessagingState: GenericStorageQuery<
      () => CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot | undefined
    >;

    /**
     * The parachain host configuration that was obtained from the relay parent.
     *
     * This field is meant to be updated each block with the validation data inherent. Therefore,
     * before processing of the inherent, e.g. in `on_initialize` this data may be stale.
     *
     * This data is also absent from the genesis.
     *
     * @param {Callback<PolkadotPrimitivesV6AbridgedHostConfiguration | undefined>=} callback
     **/
    hostConfiguration: GenericStorageQuery<() => PolkadotPrimitivesV6AbridgedHostConfiguration | undefined>;

    /**
     * The last downward message queue chain head we have observed.
     *
     * This value is loaded before and saved after processing inbound downward messages carried
     * by the system inherent.
     *
     * @param {Callback<CumulusPrimitivesParachainInherentMessageQueueChain>=} callback
     **/
    lastDmqMqcHead: GenericStorageQuery<() => CumulusPrimitivesParachainInherentMessageQueueChain>;

    /**
     * The message queue chain heads we have observed per each channel incoming channel.
     *
     * This value is loaded before and saved after processing inbound downward messages carried
     * by the system inherent.
     *
     * @param {Callback<Array<[PolkadotParachainPrimitivesPrimitivesId, CumulusPrimitivesParachainInherentMessageQueueChain]>>=} callback
     **/
    lastHrmpMqcHeads: GenericStorageQuery<
      () => Array<[PolkadotParachainPrimitivesPrimitivesId, CumulusPrimitivesParachainInherentMessageQueueChain]>
    >;

    /**
     * Number of downward messages processed in a block.
     *
     * This will be cleared in `on_initialize` of each new block.
     *
     * @param {Callback<number>=} callback
     **/
    processedDownwardMessages: GenericStorageQuery<() => number>;

    /**
     * HRMP watermark that was set in a block.
     *
     * This will be cleared in `on_initialize` of each new block.
     *
     * @param {Callback<number>=} callback
     **/
    hrmpWatermark: GenericStorageQuery<() => number>;

    /**
     * HRMP messages that were sent in a block.
     *
     * This will be cleared in `on_initialize` of each new block.
     *
     * @param {Callback<Array<PolkadotCorePrimitivesOutboundHrmpMessage>>=} callback
     **/
    hrmpOutboundMessages: GenericStorageQuery<() => Array<PolkadotCorePrimitivesOutboundHrmpMessage>>;

    /**
     * Upward messages that were sent in a block.
     *
     * This will be cleared in `on_initialize` of each new block.
     *
     * @param {Callback<Array<Bytes>>=} callback
     **/
    upwardMessages: GenericStorageQuery<() => Array<Bytes>>;

    /**
     * Upward messages that are still pending and not yet send to the relay chain.
     *
     * @param {Callback<Array<Bytes>>=} callback
     **/
    pendingUpwardMessages: GenericStorageQuery<() => Array<Bytes>>;

    /**
     * The factor to multiply the base delivery fee by for UMP.
     *
     * @param {Callback<FixedU128>=} callback
     **/
    upwardDeliveryFeeFactor: GenericStorageQuery<() => FixedU128>;

    /**
     * The number of HRMP messages we observed in `on_initialize` and thus used that number for
     * announcing the weight of `on_initialize` and `on_finalize`.
     *
     * @param {Callback<number>=} callback
     **/
    announcedHrmpMessagesPerCandidate: GenericStorageQuery<() => number>;

    /**
     * The weight we reserve at the beginning of the block for processing XCMP messages. This
     * overrides the amount set in the Config trait.
     *
     * @param {Callback<SpWeightsWeightV2Weight | undefined>=} callback
     **/
    reservedXcmpWeightOverride: GenericStorageQuery<() => SpWeightsWeightV2Weight | undefined>;

    /**
     * The weight we reserve at the beginning of the block for processing DMP messages. This
     * overrides the amount set in the Config trait.
     *
     * @param {Callback<SpWeightsWeightV2Weight | undefined>=} callback
     **/
    reservedDmpWeightOverride: GenericStorageQuery<() => SpWeightsWeightV2Weight | undefined>;

    /**
     * The next authorized upgrade, if there is one.
     *
     * @param {Callback<CumulusPalletParachainSystemCodeUpgradeAuthorization | undefined>=} callback
     **/
    authorizedUpgrade: GenericStorageQuery<() => CumulusPalletParachainSystemCodeUpgradeAuthorization | undefined>;

    /**
     * A custom head data that should be returned as result of `validate_block`.
     *
     * See `Pallet::set_custom_validation_head_data` for more information.
     *
     * @param {Callback<Bytes | undefined>=} callback
     **/
    customValidationHeadData: GenericStorageQuery<() => Bytes | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Timestamp`'s storage queries
   **/
  timestamp: {
    /**
     * The current time for the current block.
     *
     * @param {Callback<bigint>=} callback
     **/
    now: GenericStorageQuery<() => bigint>;

    /**
     * Whether the timestamp has been updated in this block.
     *
     * This value is updated to `true` upon successful submission of a timestamp by a node.
     * It is then checked at the end of each block execution in the `on_finalize` hook.
     *
     * @param {Callback<boolean>=} callback
     **/
    didUpdate: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ParachainInfo`'s storage queries
   **/
  parachainInfo: {
    /**
     *
     * @param {Callback<PolkadotParachainPrimitivesPrimitivesId>=} callback
     **/
    parachainId: GenericStorageQuery<() => PolkadotParachainPrimitivesPrimitivesId>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `RootTesting`'s storage queries
   **/
  rootTesting: {
    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Balances`'s storage queries
   **/
  balances: {
    /**
     * The total units issued in the system.
     *
     * @param {Callback<bigint>=} callback
     **/
    totalIssuance: GenericStorageQuery<() => bigint>;

    /**
     * The total units of outstanding deactivated balance in the system.
     *
     * @param {Callback<bigint>=} callback
     **/
    inactiveIssuance: GenericStorageQuery<() => bigint>;

    /**
     * The Balances pallet example of storing the balance of an account.
     *
     * # Example
     *
     * ```nocompile
     * impl pallet_balances::Config for Runtime {
     * type AccountStore = StorageMapShim<Self::Account<Runtime>, frame_system::Provider<Runtime>, AccountId, Self::AccountData<Balance>>
     * }
     * ```
     *
     * You can also store the balance of an account in the `System` pallet.
     *
     * # Example
     *
     * ```nocompile
     * impl pallet_balances::Config for Runtime {
     * type AccountStore = System
     * }
     * ```
     *
     * But this comes with tradeoffs, storing account balances in the system pallet stores
     * `frame_system` data alongside the account data contrary to storing account balances in the
     * `Balances` pallet, which uses a `StorageMap` to store balances data only.
     * NOTE: This is only used in the case that this pallet is used to store balances.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletBalancesAccountData>=} callback
     **/
    account: GenericStorageQuery<(arg: AccountId20Like) => PalletBalancesAccountData>;

    /**
     * Any liquidity locks on some account balances.
     * NOTE: Should only be accessed when setting, changing and freeing a lock.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<PalletBalancesBalanceLock>>=} callback
     **/
    locks: GenericStorageQuery<(arg: AccountId20Like) => Array<PalletBalancesBalanceLock>>;

    /**
     * Named reserves on some account balances.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<PalletBalancesReserveData>>=} callback
     **/
    reserves: GenericStorageQuery<(arg: AccountId20Like) => Array<PalletBalancesReserveData>>;

    /**
     * Holds on account balances.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<PalletBalancesIdAmount>>=} callback
     **/
    holds: GenericStorageQuery<(arg: AccountId20Like) => Array<PalletBalancesIdAmount>>;

    /**
     * Freeze locks on account balances.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<PalletBalancesIdAmount002>>=} callback
     **/
    freezes: GenericStorageQuery<(arg: AccountId20Like) => Array<PalletBalancesIdAmount002>>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `TransactionPayment`'s storage queries
   **/
  transactionPayment: {
    /**
     *
     * @param {Callback<FixedU128>=} callback
     **/
    nextFeeMultiplier: GenericStorageQuery<() => FixedU128>;

    /**
     *
     * @param {Callback<PalletTransactionPaymentReleases>=} callback
     **/
    storageVersion: GenericStorageQuery<() => PalletTransactionPaymentReleases>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ParachainStaking`'s storage queries
   **/
  parachainStaking: {
    /**
     * Commission percent taken off of rewards for all collators
     *
     * @param {Callback<Perbill>=} callback
     **/
    collatorCommission: GenericStorageQuery<() => Perbill>;

    /**
     * The total candidates selected every round
     *
     * @param {Callback<number>=} callback
     **/
    totalSelected: GenericStorageQuery<() => number>;

    /**
     * Parachain bond config info { account, percent_of_inflation }
     *
     * @param {Callback<PalletParachainStakingParachainBondConfig>=} callback
     **/
    parachainBondInfo: GenericStorageQuery<() => PalletParachainStakingParachainBondConfig>;

    /**
     * Current round index and next round scheduled transition
     *
     * @param {Callback<PalletParachainStakingRoundInfo>=} callback
     **/
    round: GenericStorageQuery<() => PalletParachainStakingRoundInfo>;

    /**
     * Get delegator state associated with an account if account is delegating else None
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletParachainStakingDelegator | undefined>=} callback
     **/
    delegatorState: GenericStorageQuery<(arg: AccountId20Like) => PalletParachainStakingDelegator | undefined>;

    /**
     * Get collator candidate info associated with an account if account is candidate else None
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletParachainStakingCandidateMetadata | undefined>=} callback
     **/
    candidateInfo: GenericStorageQuery<(arg: AccountId20Like) => PalletParachainStakingCandidateMetadata | undefined>;

    /**
     * Stores outstanding delegation requests per collator.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<PalletParachainStakingDelegationRequestsScheduledRequest>>=} callback
     **/
    delegationScheduledRequests: GenericStorageQuery<
      (arg: AccountId20Like) => Array<PalletParachainStakingDelegationRequestsScheduledRequest>
    >;

    /**
     * Stores auto-compounding configuration per collator.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<PalletParachainStakingAutoCompoundAutoCompoundConfig>>=} callback
     **/
    autoCompoundingDelegations: GenericStorageQuery<
      (arg: AccountId20Like) => Array<PalletParachainStakingAutoCompoundAutoCompoundConfig>
    >;

    /**
     * Top delegations for collator candidate
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletParachainStakingDelegations | undefined>=} callback
     **/
    topDelegations: GenericStorageQuery<(arg: AccountId20Like) => PalletParachainStakingDelegations | undefined>;

    /**
     * Bottom delegations for collator candidate
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletParachainStakingDelegations | undefined>=} callback
     **/
    bottomDelegations: GenericStorageQuery<(arg: AccountId20Like) => PalletParachainStakingDelegations | undefined>;

    /**
     * The collator candidates selected for the current round
     *
     * @param {Callback<Array<AccountId20>>=} callback
     **/
    selectedCandidates: GenericStorageQuery<() => Array<AccountId20>>;

    /**
     * Total capital locked by this staking pallet
     *
     * @param {Callback<bigint>=} callback
     **/
    total: GenericStorageQuery<() => bigint>;

    /**
     * The pool of collator candidates, each with their total backing stake
     *
     * @param {Callback<PalletParachainStakingSetBoundedOrderedSet>=} callback
     **/
    candidatePool: GenericStorageQuery<() => PalletParachainStakingSetBoundedOrderedSet>;

    /**
     * Snapshot of collator delegation stake at the start of the round
     *
     * @param {[number, AccountId20Like]} arg
     * @param {Callback<PalletParachainStakingCollatorSnapshot | undefined>=} callback
     **/
    atStake: GenericStorageQuery<
      (arg: [number, AccountId20Like]) => PalletParachainStakingCollatorSnapshot | undefined
    >;

    /**
     * Delayed payouts
     *
     * @param {number} arg
     * @param {Callback<PalletParachainStakingDelayedPayout | undefined>=} callback
     **/
    delayedPayouts: GenericStorageQuery<(arg: number) => PalletParachainStakingDelayedPayout | undefined>;

    /**
     * Total counted stake for selected candidates in the round
     *
     * @param {number} arg
     * @param {Callback<bigint>=} callback
     **/
    staked: GenericStorageQuery<(arg: number) => bigint>;

    /**
     * Inflation configuration
     *
     * @param {Callback<PalletParachainStakingInflationInflationInfo>=} callback
     **/
    inflationConfig: GenericStorageQuery<() => PalletParachainStakingInflationInflationInfo>;

    /**
     * Total points awarded to collators for block production in the round
     *
     * @param {number} arg
     * @param {Callback<number>=} callback
     **/
    points: GenericStorageQuery<(arg: number) => number>;

    /**
     * Points for each collator per round
     *
     * @param {[number, AccountId20Like]} arg
     * @param {Callback<number>=} callback
     **/
    awardedPts: GenericStorageQuery<(arg: [number, AccountId20Like]) => number>;

    /**
     * Killswitch to enable/disable marking offline feature.
     *
     * @param {Callback<boolean>=} callback
     **/
    enableMarkingOffline: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `AuthorInherent`'s storage queries
   **/
  authorInherent: {
    /**
     * Author of current block.
     *
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    author: GenericStorageQuery<() => AccountId20 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `AuthorFilter`'s storage queries
   **/
  authorFilter: {
    /**
     *
     * @param {Callback<Percent>=} callback
     **/
    eligibleRatio: GenericStorageQuery<() => Percent>;

    /**
     * The number of active authors that will be eligible at each height.
     *
     * @param {Callback<PalletAuthorSlotFilterNumNonZeroU32>=} callback
     **/
    eligibleCount: GenericStorageQuery<() => PalletAuthorSlotFilterNumNonZeroU32>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `AuthorMapping`'s storage queries
   **/
  authorMapping: {
    /**
     * We maintain a mapping from the NimbusIds used in the consensus layer
     * to the AccountIds runtime.
     *
     * @param {NimbusPrimitivesNimbusCryptoPublic} arg
     * @param {Callback<PalletAuthorMappingRegistrationInfo | undefined>=} callback
     **/
    mappingWithDeposit: GenericStorageQuery<
      (arg: NimbusPrimitivesNimbusCryptoPublic) => PalletAuthorMappingRegistrationInfo | undefined
    >;

    /**
     * We maintain a reverse mapping from AccountIds to NimbusIDS
     *
     * @param {AccountId20Like} arg
     * @param {Callback<NimbusPrimitivesNimbusCryptoPublic | undefined>=} callback
     **/
    nimbusLookup: GenericStorageQuery<(arg: AccountId20Like) => NimbusPrimitivesNimbusCryptoPublic | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `MoonbeamOrbiters`'s storage queries
   **/
  moonbeamOrbiters: {
    /**
     * Account lookup override
     *
     * @param {AccountId20Like} arg
     * @param {Callback<AccountId20 | undefined | undefined>=} callback
     **/
    accountLookupOverride: GenericStorageQuery<(arg: AccountId20Like) => AccountId20 | undefined | undefined>;

    /**
     * Current orbiters, with their "parent" collator
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletMoonbeamOrbitersCollatorPoolInfo | undefined>=} callback
     **/
    collatorsPool: GenericStorageQuery<(arg: AccountId20Like) => PalletMoonbeamOrbitersCollatorPoolInfo | undefined>;

    /**
     * Counter for the related counted storage map
     *
     * @param {Callback<number>=} callback
     **/
    counterForCollatorsPool: GenericStorageQuery<() => number>;

    /**
     * Current round index
     *
     * @param {Callback<number>=} callback
     **/
    currentRound: GenericStorageQuery<() => number>;

    /**
     * If true, it forces the rotation at the next round.
     * A use case: when changing RotatePeriod, you need a migration code that sets this value to
     * true to avoid holes in OrbiterPerRound.
     *
     * @param {Callback<boolean>=} callback
     **/
    forceRotation: GenericStorageQuery<() => boolean>;

    /**
     * Minimum deposit required to be registered as an orbiter
     *
     * @param {Callback<bigint | undefined>=} callback
     **/
    minOrbiterDeposit: GenericStorageQuery<() => bigint | undefined>;

    /**
     * Store active orbiter per round and per parent collator
     *
     * @param {[number, AccountId20Like]} arg
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    orbiterPerRound: GenericStorageQuery<(arg: [number, AccountId20Like]) => AccountId20 | undefined>;

    /**
     * Check if account is an orbiter
     *
     * @param {AccountId20Like} arg
     * @param {Callback<boolean | undefined>=} callback
     **/
    registeredOrbiter: GenericStorageQuery<(arg: AccountId20Like) => boolean | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Proxy`'s storage queries
   **/
  proxy: {
    /**
     * The set of account proxies. Maps the account which has delegated to the accounts
     * which are being delegated to, together with the amount held on deposit.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<[Array<PalletProxyProxyDefinition>, bigint]>=} callback
     **/
    proxies: GenericStorageQuery<(arg: AccountId20Like) => [Array<PalletProxyProxyDefinition>, bigint]>;

    /**
     * The announcements made by the proxy (key).
     *
     * @param {AccountId20Like} arg
     * @param {Callback<[Array<PalletProxyAnnouncement>, bigint]>=} callback
     **/
    announcements: GenericStorageQuery<(arg: AccountId20Like) => [Array<PalletProxyAnnouncement>, bigint]>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `MaintenanceMode`'s storage queries
   **/
  maintenanceMode: {
    /**
     * Whether the site is in maintenance mode
     *
     * @param {Callback<boolean>=} callback
     **/
    maintenanceMode: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Identity`'s storage queries
   **/
  identity: {
    /**
     * Information that is pertinent to identify the entity behind an account.
     *
     * TWOX-NOTE: OK ― `AccountId` is a secure hash.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletIdentityRegistration | undefined>=} callback
     **/
    identityOf: GenericStorageQuery<(arg: AccountId20Like) => PalletIdentityRegistration | undefined>;

    /**
     * The super-identity of an alternative "sub" identity together with its name, within that
     * context. If the account is not some other account's sub-identity, then just `None`.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<[AccountId20, Data] | undefined>=} callback
     **/
    superOf: GenericStorageQuery<(arg: AccountId20Like) => [AccountId20, Data] | undefined>;

    /**
     * Alternative "sub" identities of this account.
     *
     * The first item is the deposit, the second is a vector of the accounts.
     *
     * TWOX-NOTE: OK ― `AccountId` is a secure hash.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<[bigint, Array<AccountId20>]>=} callback
     **/
    subsOf: GenericStorageQuery<(arg: AccountId20Like) => [bigint, Array<AccountId20>]>;

    /**
     * The set of registrars. Not expected to get very big as can only be added through a
     * special origin (likely a council motion).
     *
     * The index into this can be cast to `RegistrarIndex` to get a valid value.
     *
     * @param {Callback<Array<PalletIdentityRegistrarInfo | undefined>>=} callback
     **/
    registrars: GenericStorageQuery<() => Array<PalletIdentityRegistrarInfo | undefined>>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Migrations`'s storage queries
   **/
  migrations: {
    /**
     * True if all required migrations have completed
     *
     * @param {Callback<boolean>=} callback
     **/
    fullyUpgraded: GenericStorageQuery<() => boolean>;

    /**
     * MigrationState tracks the progress of a migration.
     * Maps name (Vec<u8>) -> whether or not migration has been completed (bool)
     *
     * @param {BytesLike} arg
     * @param {Callback<boolean>=} callback
     **/
    migrationState: GenericStorageQuery<(arg: BytesLike) => boolean>;

    /**
     * Temporary value that is set to true at the beginning of the block during which the execution
     * of xcm messages must be paused.
     *
     * @param {Callback<boolean>=} callback
     **/
    shouldPauseXcm: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Multisig`'s storage queries
   **/
  multisig: {
    /**
     * The set of open multisig operations.
     *
     * @param {[AccountId20Like, FixedBytes<32>]} arg
     * @param {Callback<PalletMultisigMultisig | undefined>=} callback
     **/
    multisigs: GenericStorageQuery<(arg: [AccountId20Like, FixedBytes<32>]) => PalletMultisigMultisig | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `EthereumChainId`'s storage queries
   **/
  ethereumChainId: {
    /**
     * The EVM chain ID.
     *
     * @param {Callback<bigint>=} callback
     **/
    chainId: GenericStorageQuery<() => bigint>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `EVM`'s storage queries
   **/
  eVM: {
    /**
     *
     * @param {H160} arg
     * @param {Callback<Bytes>=} callback
     **/
    accountCodes: GenericStorageQuery<(arg: H160) => Bytes>;

    /**
     *
     * @param {H160} arg
     * @param {Callback<PalletEvmCodeMetadata | undefined>=} callback
     **/
    accountCodesMetadata: GenericStorageQuery<(arg: H160) => PalletEvmCodeMetadata | undefined>;

    /**
     *
     * @param {[H160, H256]} arg
     * @param {Callback<H256>=} callback
     **/
    accountStorages: GenericStorageQuery<(arg: [H160, H256]) => H256>;

    /**
     *
     * @param {H160} arg
     * @param {Callback<[] | undefined>=} callback
     **/
    suicided: GenericStorageQuery<(arg: H160) => [] | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Ethereum`'s storage queries
   **/
  ethereum: {
    /**
     * Current building block's transactions and receipts.
     *
     * @param {Callback<Array<[EthereumTransactionTransactionV2, FpRpcTransactionStatus, EthereumReceiptReceiptV3]>>=} callback
     **/
    pending: GenericStorageQuery<
      () => Array<[EthereumTransactionTransactionV2, FpRpcTransactionStatus, EthereumReceiptReceiptV3]>
    >;

    /**
     * The current Ethereum block.
     *
     * @param {Callback<EthereumBlock | undefined>=} callback
     **/
    currentBlock: GenericStorageQuery<() => EthereumBlock | undefined>;

    /**
     * The current Ethereum receipts.
     *
     * @param {Callback<Array<EthereumReceiptReceiptV3> | undefined>=} callback
     **/
    currentReceipts: GenericStorageQuery<() => Array<EthereumReceiptReceiptV3> | undefined>;

    /**
     * The current transaction statuses.
     *
     * @param {Callback<Array<FpRpcTransactionStatus> | undefined>=} callback
     **/
    currentTransactionStatuses: GenericStorageQuery<() => Array<FpRpcTransactionStatus> | undefined>;

    /**
     *
     * @param {U256} arg
     * @param {Callback<H256>=} callback
     **/
    blockHash: GenericStorageQuery<(arg: U256) => H256>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Scheduler`'s storage queries
   **/
  scheduler: {
    /**
     *
     * @param {Callback<number | undefined>=} callback
     **/
    incompleteSince: GenericStorageQuery<() => number | undefined>;

    /**
     * Items to be executed, indexed by the block number that they should be executed on.
     *
     * @param {number} arg
     * @param {Callback<Array<PalletSchedulerScheduled | undefined>>=} callback
     **/
    agenda: GenericStorageQuery<(arg: number) => Array<PalletSchedulerScheduled | undefined>>;

    /**
     * Lookup from a name to the block number and index of the task.
     *
     * For v3 -> v4 the previously unbounded identities are Blake2-256 hashed to form the v4
     * identities.
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<[number, number] | undefined>=} callback
     **/
    lookup: GenericStorageQuery<(arg: FixedBytes<32>) => [number, number] | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Democracy`'s storage queries
   **/
  democracy: {
    /**
     * The number of (public) proposals that have been made so far.
     *
     * @param {Callback<number>=} callback
     **/
    publicPropCount: GenericStorageQuery<() => number>;

    /**
     * The public proposals. Unsorted. The second item is the proposal.
     *
     * @param {Callback<Array<[number, FrameSupportPreimagesBounded, AccountId20]>>=} callback
     **/
    publicProps: GenericStorageQuery<() => Array<[number, FrameSupportPreimagesBounded, AccountId20]>>;

    /**
     * Those who have locked a deposit.
     *
     * TWOX-NOTE: Safe, as increasing integer keys are safe.
     *
     * @param {number} arg
     * @param {Callback<[Array<AccountId20>, bigint] | undefined>=} callback
     **/
    depositOf: GenericStorageQuery<(arg: number) => [Array<AccountId20>, bigint] | undefined>;

    /**
     * The next free referendum index, aka the number of referenda started so far.
     *
     * @param {Callback<number>=} callback
     **/
    referendumCount: GenericStorageQuery<() => number>;

    /**
     * The lowest referendum index representing an unbaked referendum. Equal to
     * `ReferendumCount` if there isn't a unbaked referendum.
     *
     * @param {Callback<number>=} callback
     **/
    lowestUnbaked: GenericStorageQuery<() => number>;

    /**
     * Information concerning any given referendum.
     *
     * TWOX-NOTE: SAFE as indexes are not under an attacker’s control.
     *
     * @param {number} arg
     * @param {Callback<PalletDemocracyReferendumInfo | undefined>=} callback
     **/
    referendumInfoOf: GenericStorageQuery<(arg: number) => PalletDemocracyReferendumInfo | undefined>;

    /**
     * All votes for a particular voter. We store the balance for the number of votes that we
     * have recorded. The second item is the total amount of delegations, that will be added.
     *
     * TWOX-NOTE: SAFE as `AccountId`s are crypto hashes anyway.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletDemocracyVoteVoting>=} callback
     **/
    votingOf: GenericStorageQuery<(arg: AccountId20Like) => PalletDemocracyVoteVoting>;

    /**
     * True if the last referendum tabled was submitted externally. False if it was a public
     * proposal.
     *
     * @param {Callback<boolean>=} callback
     **/
    lastTabledWasExternal: GenericStorageQuery<() => boolean>;

    /**
     * The referendum to be tabled whenever it would be valid to table an external proposal.
     * This happens when a referendum needs to be tabled and one of two conditions are met:
     * - `LastTabledWasExternal` is `false`; or
     * - `PublicProps` is empty.
     *
     * @param {Callback<[FrameSupportPreimagesBounded, PalletDemocracyVoteThreshold] | undefined>=} callback
     **/
    nextExternal: GenericStorageQuery<() => [FrameSupportPreimagesBounded, PalletDemocracyVoteThreshold] | undefined>;

    /**
     * A record of who vetoed what. Maps proposal hash to a possible existent block number
     * (until when it may not be resubmitted) and who vetoed it.
     *
     * @param {H256} arg
     * @param {Callback<[number, Array<AccountId20>] | undefined>=} callback
     **/
    blacklist: GenericStorageQuery<(arg: H256) => [number, Array<AccountId20>] | undefined>;

    /**
     * Record of all proposals that have been subject to emergency cancellation.
     *
     * @param {H256} arg
     * @param {Callback<boolean>=} callback
     **/
    cancellations: GenericStorageQuery<(arg: H256) => boolean>;

    /**
     * General information concerning any proposal or referendum.
     * The `Hash` refers to the preimage of the `Preimages` provider which can be a JSON
     * dump or IPFS hash of a JSON file.
     *
     * Consider a garbage collection for a metadata of finished referendums to `unrequest` (remove)
     * large preimages.
     *
     * @param {PalletDemocracyMetadataOwner} arg
     * @param {Callback<H256 | undefined>=} callback
     **/
    metadataOf: GenericStorageQuery<(arg: PalletDemocracyMetadataOwner) => H256 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Preimage`'s storage queries
   **/
  preimage: {
    /**
     * The request status of a given hash.
     *
     * @param {H256} arg
     * @param {Callback<PalletPreimageOldRequestStatus | undefined>=} callback
     **/
    statusFor: GenericStorageQuery<(arg: H256) => PalletPreimageOldRequestStatus | undefined>;

    /**
     * The request status of a given hash.
     *
     * @param {H256} arg
     * @param {Callback<PalletPreimageRequestStatus | undefined>=} callback
     **/
    requestStatusFor: GenericStorageQuery<(arg: H256) => PalletPreimageRequestStatus | undefined>;

    /**
     *
     * @param {[H256, number]} arg
     * @param {Callback<Bytes | undefined>=} callback
     **/
    preimageFor: GenericStorageQuery<(arg: [H256, number]) => Bytes | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `ConvictionVoting`'s storage queries
   **/
  convictionVoting: {
    /**
     * All voting for a particular voter in a particular voting class. We store the balance for the
     * number of votes that we have recorded.
     *
     * @param {[AccountId20Like, number]} arg
     * @param {Callback<PalletConvictionVotingVoteVoting>=} callback
     **/
    votingFor: GenericStorageQuery<(arg: [AccountId20Like, number]) => PalletConvictionVotingVoteVoting>;

    /**
     * The voting classes which have a non-zero lock requirement and the lock amounts which they
     * require. The actual amount locked on behalf of this pallet should always be the maximum of
     * this list.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<[number, bigint]>>=} callback
     **/
    classLocksFor: GenericStorageQuery<(arg: AccountId20Like) => Array<[number, bigint]>>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Referenda`'s storage queries
   **/
  referenda: {
    /**
     * The next free referendum index, aka the number of referenda started so far.
     *
     * @param {Callback<number>=} callback
     **/
    referendumCount: GenericStorageQuery<() => number>;

    /**
     * Information concerning any given referendum.
     *
     * @param {number} arg
     * @param {Callback<PalletReferendaReferendumInfo | undefined>=} callback
     **/
    referendumInfoFor: GenericStorageQuery<(arg: number) => PalletReferendaReferendumInfo | undefined>;

    /**
     * The sorted list of referenda ready to be decided but not yet being decided, ordered by
     * conviction-weighted approvals.
     *
     * This should be empty if `DecidingCount` is less than `TrackInfo::max_deciding`.
     *
     * @param {number} arg
     * @param {Callback<Array<[number, bigint]>>=} callback
     **/
    trackQueue: GenericStorageQuery<(arg: number) => Array<[number, bigint]>>;

    /**
     * The number of referenda being decided currently.
     *
     * @param {number} arg
     * @param {Callback<number>=} callback
     **/
    decidingCount: GenericStorageQuery<(arg: number) => number>;

    /**
     * The metadata is a general information concerning the referendum.
     * The `Hash` refers to the preimage of the `Preimages` provider which can be a JSON
     * dump or IPFS hash of a JSON file.
     *
     * Consider a garbage collection for a metadata of finished referendums to `unrequest` (remove)
     * large preimages.
     *
     * @param {number} arg
     * @param {Callback<H256 | undefined>=} callback
     **/
    metadataOf: GenericStorageQuery<(arg: number) => H256 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Whitelist`'s storage queries
   **/
  whitelist: {
    /**
     *
     * @param {H256} arg
     * @param {Callback<[] | undefined>=} callback
     **/
    whitelistedCall: GenericStorageQuery<(arg: H256) => [] | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `CouncilCollective`'s storage queries
   **/
  councilCollective: {
    /**
     * The hashes of the active proposals.
     *
     * @param {Callback<Array<H256>>=} callback
     **/
    proposals: GenericStorageQuery<() => Array<H256>>;

    /**
     * Actual proposal for a given hash, if it's current.
     *
     * @param {H256} arg
     * @param {Callback<MoonbeamRuntimeRuntimeCall | undefined>=} callback
     **/
    proposalOf: GenericStorageQuery<(arg: H256) => MoonbeamRuntimeRuntimeCall | undefined>;

    /**
     * Votes on a given proposal, if it is ongoing.
     *
     * @param {H256} arg
     * @param {Callback<PalletCollectiveVotes | undefined>=} callback
     **/
    voting: GenericStorageQuery<(arg: H256) => PalletCollectiveVotes | undefined>;

    /**
     * Proposals so far.
     *
     * @param {Callback<number>=} callback
     **/
    proposalCount: GenericStorageQuery<() => number>;

    /**
     * The current members of the collective. This is stored sorted (just by value).
     *
     * @param {Callback<Array<AccountId20>>=} callback
     **/
    members: GenericStorageQuery<() => Array<AccountId20>>;

    /**
     * The prime member that helps determine the default vote behavior in case of absentations.
     *
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    prime: GenericStorageQuery<() => AccountId20 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `TechCommitteeCollective`'s storage queries
   **/
  techCommitteeCollective: {
    /**
     * The hashes of the active proposals.
     *
     * @param {Callback<Array<H256>>=} callback
     **/
    proposals: GenericStorageQuery<() => Array<H256>>;

    /**
     * Actual proposal for a given hash, if it's current.
     *
     * @param {H256} arg
     * @param {Callback<MoonbeamRuntimeRuntimeCall | undefined>=} callback
     **/
    proposalOf: GenericStorageQuery<(arg: H256) => MoonbeamRuntimeRuntimeCall | undefined>;

    /**
     * Votes on a given proposal, if it is ongoing.
     *
     * @param {H256} arg
     * @param {Callback<PalletCollectiveVotes | undefined>=} callback
     **/
    voting: GenericStorageQuery<(arg: H256) => PalletCollectiveVotes | undefined>;

    /**
     * Proposals so far.
     *
     * @param {Callback<number>=} callback
     **/
    proposalCount: GenericStorageQuery<() => number>;

    /**
     * The current members of the collective. This is stored sorted (just by value).
     *
     * @param {Callback<Array<AccountId20>>=} callback
     **/
    members: GenericStorageQuery<() => Array<AccountId20>>;

    /**
     * The prime member that helps determine the default vote behavior in case of absentations.
     *
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    prime: GenericStorageQuery<() => AccountId20 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `TreasuryCouncilCollective`'s storage queries
   **/
  treasuryCouncilCollective: {
    /**
     * The hashes of the active proposals.
     *
     * @param {Callback<Array<H256>>=} callback
     **/
    proposals: GenericStorageQuery<() => Array<H256>>;

    /**
     * Actual proposal for a given hash, if it's current.
     *
     * @param {H256} arg
     * @param {Callback<MoonbeamRuntimeRuntimeCall | undefined>=} callback
     **/
    proposalOf: GenericStorageQuery<(arg: H256) => MoonbeamRuntimeRuntimeCall | undefined>;

    /**
     * Votes on a given proposal, if it is ongoing.
     *
     * @param {H256} arg
     * @param {Callback<PalletCollectiveVotes | undefined>=} callback
     **/
    voting: GenericStorageQuery<(arg: H256) => PalletCollectiveVotes | undefined>;

    /**
     * Proposals so far.
     *
     * @param {Callback<number>=} callback
     **/
    proposalCount: GenericStorageQuery<() => number>;

    /**
     * The current members of the collective. This is stored sorted (just by value).
     *
     * @param {Callback<Array<AccountId20>>=} callback
     **/
    members: GenericStorageQuery<() => Array<AccountId20>>;

    /**
     * The prime member that helps determine the default vote behavior in case of absentations.
     *
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    prime: GenericStorageQuery<() => AccountId20 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `OpenTechCommitteeCollective`'s storage queries
   **/
  openTechCommitteeCollective: {
    /**
     * The hashes of the active proposals.
     *
     * @param {Callback<Array<H256>>=} callback
     **/
    proposals: GenericStorageQuery<() => Array<H256>>;

    /**
     * Actual proposal for a given hash, if it's current.
     *
     * @param {H256} arg
     * @param {Callback<MoonbeamRuntimeRuntimeCall | undefined>=} callback
     **/
    proposalOf: GenericStorageQuery<(arg: H256) => MoonbeamRuntimeRuntimeCall | undefined>;

    /**
     * Votes on a given proposal, if it is ongoing.
     *
     * @param {H256} arg
     * @param {Callback<PalletCollectiveVotes | undefined>=} callback
     **/
    voting: GenericStorageQuery<(arg: H256) => PalletCollectiveVotes | undefined>;

    /**
     * Proposals so far.
     *
     * @param {Callback<number>=} callback
     **/
    proposalCount: GenericStorageQuery<() => number>;

    /**
     * The current members of the collective. This is stored sorted (just by value).
     *
     * @param {Callback<Array<AccountId20>>=} callback
     **/
    members: GenericStorageQuery<() => Array<AccountId20>>;

    /**
     * The prime member that helps determine the default vote behavior in case of absentations.
     *
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    prime: GenericStorageQuery<() => AccountId20 | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Treasury`'s storage queries
   **/
  treasury: {
    /**
     * Number of proposals that have been made.
     *
     * @param {Callback<number>=} callback
     **/
    proposalCount: GenericStorageQuery<() => number>;

    /**
     * Proposals that have been made.
     *
     * @param {number} arg
     * @param {Callback<PalletTreasuryProposal | undefined>=} callback
     **/
    proposals: GenericStorageQuery<(arg: number) => PalletTreasuryProposal | undefined>;

    /**
     * The amount which has been reported as inactive to Currency.
     *
     * @param {Callback<bigint>=} callback
     **/
    deactivated: GenericStorageQuery<() => bigint>;

    /**
     * Proposal indices that have been approved but not yet awarded.
     *
     * @param {Callback<Array<number>>=} callback
     **/
    approvals: GenericStorageQuery<() => Array<number>>;

    /**
     * The count of spends that have been made.
     *
     * @param {Callback<number>=} callback
     **/
    spendCount: GenericStorageQuery<() => number>;

    /**
     * Spends that have been approved and being processed.
     *
     * @param {number} arg
     * @param {Callback<PalletTreasurySpendStatus | undefined>=} callback
     **/
    spends: GenericStorageQuery<(arg: number) => PalletTreasurySpendStatus | undefined>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `CrowdloanRewards`'s storage queries
   **/
  crowdloanRewards: {
    /**
     *
     * @param {AccountId20Like} arg
     * @param {Callback<PalletCrowdloanRewardsRewardInfo | undefined>=} callback
     **/
    accountsPayable: GenericStorageQuery<(arg: AccountId20Like) => PalletCrowdloanRewardsRewardInfo | undefined>;

    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<[] | undefined>=} callback
     **/
    claimedRelayChainIds: GenericStorageQuery<(arg: FixedBytes<32>) => [] | undefined>;

    /**
     *
     * @param {FixedBytes<32>} arg
     * @param {Callback<PalletCrowdloanRewardsRewardInfo | undefined>=} callback
     **/
    unassociatedContributions: GenericStorageQuery<
      (arg: FixedBytes<32>) => PalletCrowdloanRewardsRewardInfo | undefined
    >;

    /**
     *
     * @param {Callback<boolean>=} callback
     **/
    initialized: GenericStorageQuery<() => boolean>;

    /**
     * Vesting block height at the initialization of the pallet
     *
     * @param {Callback<number>=} callback
     **/
    initRelayBlock: GenericStorageQuery<() => number>;

    /**
     * Vesting block height at the initialization of the pallet
     *
     * @param {Callback<number>=} callback
     **/
    endRelayBlock: GenericStorageQuery<() => number>;

    /**
     * Total initialized amount so far. We store this to make pallet funds == contributors reward
     * check easier and more efficient
     *
     * @param {Callback<bigint>=} callback
     **/
    initializedRewardAmount: GenericStorageQuery<() => bigint>;

    /**
     * Total number of contributors to aid hinting benchmarking
     *
     * @param {Callback<number>=} callback
     **/
    totalContributors: GenericStorageQuery<() => number>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `XcmpQueue`'s storage queries
   **/
  xcmpQueue: {
    /**
     * Status of the inbound XCMP channels.
     *
     * @param {Callback<Array<CumulusPalletXcmpQueueInboundChannelDetails>>=} callback
     **/
    inboundXcmpStatus: GenericStorageQuery<() => Array<CumulusPalletXcmpQueueInboundChannelDetails>>;

    /**
     * Inbound aggregate XCMP messages. It can only be one per ParaId/block.
     *
     * @param {[PolkadotParachainPrimitivesPrimitivesId, number]} arg
     * @param {Callback<Bytes>=} callback
     **/
    inboundXcmpMessages: GenericStorageQuery<(arg: [PolkadotParachainPrimitivesPrimitivesId, number]) => Bytes>;

    /**
     * The non-empty XCMP channels in order of becoming non-empty, and the index of the first
     * and last outbound message. If the two indices are equal, then it indicates an empty
     * queue and there must be a non-`Ok` `OutboundStatus`. We assume queues grow no greater
     * than 65535 items. Queue indices for normal messages begin at one; zero is reserved in
     * case of the need to send a high-priority signal message this block.
     * The bool is true if there is a signal message waiting to be sent.
     *
     * @param {Callback<Array<CumulusPalletXcmpQueueOutboundChannelDetails>>=} callback
     **/
    outboundXcmpStatus: GenericStorageQuery<() => Array<CumulusPalletXcmpQueueOutboundChannelDetails>>;

    /**
     * The messages outbound in a given XCMP channel.
     *
     * @param {[PolkadotParachainPrimitivesPrimitivesId, number]} arg
     * @param {Callback<Bytes>=} callback
     **/
    outboundXcmpMessages: GenericStorageQuery<(arg: [PolkadotParachainPrimitivesPrimitivesId, number]) => Bytes>;

    /**
     * Any signal messages waiting to be sent.
     *
     * @param {PolkadotParachainPrimitivesPrimitivesId} arg
     * @param {Callback<Bytes>=} callback
     **/
    signalMessages: GenericStorageQuery<(arg: PolkadotParachainPrimitivesPrimitivesId) => Bytes>;

    /**
     * The configuration which controls the dynamics of the outbound queue.
     *
     * @param {Callback<CumulusPalletXcmpQueueQueueConfigData>=} callback
     **/
    queueConfig: GenericStorageQuery<() => CumulusPalletXcmpQueueQueueConfigData>;

    /**
     * The messages that exceeded max individual message weight budget.
     *
     * These message stay in this storage map until they are manually dispatched via
     * `service_overweight`.
     *
     * @param {bigint} arg
     * @param {Callback<[PolkadotParachainPrimitivesPrimitivesId, number, Bytes] | undefined>=} callback
     **/
    overweight: GenericStorageQuery<
      (arg: bigint) => [PolkadotParachainPrimitivesPrimitivesId, number, Bytes] | undefined
    >;

    /**
     * Counter for the related counted storage map
     *
     * @param {Callback<number>=} callback
     **/
    counterForOverweight: GenericStorageQuery<() => number>;

    /**
     * The number of overweight messages ever recorded in `Overweight`. Also doubles as the next
     * available free overweight index.
     *
     * @param {Callback<bigint>=} callback
     **/
    overweightCount: GenericStorageQuery<() => bigint>;

    /**
     * Whether or not the XCMP queue is suspended from executing incoming XCMs or not.
     *
     * @param {Callback<boolean>=} callback
     **/
    queueSuspended: GenericStorageQuery<() => boolean>;

    /**
     * The factor to multiply the base delivery fee by.
     *
     * @param {PolkadotParachainPrimitivesPrimitivesId} arg
     * @param {Callback<FixedU128>=} callback
     **/
    deliveryFeeFactor: GenericStorageQuery<(arg: PolkadotParachainPrimitivesPrimitivesId) => FixedU128>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `DmpQueue`'s storage queries
   **/
  dmpQueue: {
    /**
     * The configuration.
     *
     * @param {Callback<CumulusPalletDmpQueueConfigData>=} callback
     **/
    configuration: GenericStorageQuery<() => CumulusPalletDmpQueueConfigData>;

    /**
     * The page index.
     *
     * @param {Callback<CumulusPalletDmpQueuePageIndexData>=} callback
     **/
    pageIndex: GenericStorageQuery<() => CumulusPalletDmpQueuePageIndexData>;

    /**
     * The queue pages.
     *
     * @param {number} arg
     * @param {Callback<Array<[number, Bytes]>>=} callback
     **/
    pages: GenericStorageQuery<(arg: number) => Array<[number, Bytes]>>;

    /**
     * The overweight messages.
     *
     * @param {bigint} arg
     * @param {Callback<[number, Bytes] | undefined>=} callback
     **/
    overweight: GenericStorageQuery<(arg: bigint) => [number, Bytes] | undefined>;

    /**
     * Counter for the related counted storage map
     *
     * @param {Callback<number>=} callback
     **/
    counterForOverweight: GenericStorageQuery<() => number>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `PolkadotXcm`'s storage queries
   **/
  polkadotXcm: {
    /**
     * The latest available query index.
     *
     * @param {Callback<bigint>=} callback
     **/
    queryCounter: GenericStorageQuery<() => bigint>;

    /**
     * The ongoing queries.
     *
     * @param {bigint} arg
     * @param {Callback<PalletXcmQueryStatus | undefined>=} callback
     **/
    queries: GenericStorageQuery<(arg: bigint) => PalletXcmQueryStatus | undefined>;

    /**
     * The existing asset traps.
     *
     * Key is the blake2 256 hash of (origin, versioned `MultiAssets`) pair. Value is the number of
     * times this pair has been trapped (usually just 1 if it exists at all).
     *
     * @param {H256} arg
     * @param {Callback<number>=} callback
     **/
    assetTraps: GenericStorageQuery<(arg: H256) => number>;

    /**
     * Default version to encode XCM when latest version of destination is unknown. If `None`,
     * then the destinations whose XCM version is unknown are considered unreachable.
     *
     * @param {Callback<number | undefined>=} callback
     **/
    safeXcmVersion: GenericStorageQuery<() => number | undefined>;

    /**
     * The Latest versions that we know various locations support.
     *
     * @param {[number, XcmVersionedMultiLocation]} arg
     * @param {Callback<number | undefined>=} callback
     **/
    supportedVersion: GenericStorageQuery<(arg: [number, XcmVersionedMultiLocation]) => number | undefined>;

    /**
     * All locations that we have requested version notifications from.
     *
     * @param {[number, XcmVersionedMultiLocation]} arg
     * @param {Callback<bigint | undefined>=} callback
     **/
    versionNotifiers: GenericStorageQuery<(arg: [number, XcmVersionedMultiLocation]) => bigint | undefined>;

    /**
     * The target locations that are subscribed to our version changes, as well as the most recent
     * of our versions we informed them of.
     *
     * @param {[number, XcmVersionedMultiLocation]} arg
     * @param {Callback<[bigint, SpWeightsWeightV2Weight, number] | undefined>=} callback
     **/
    versionNotifyTargets: GenericStorageQuery<
      (arg: [number, XcmVersionedMultiLocation]) => [bigint, SpWeightsWeightV2Weight, number] | undefined
    >;

    /**
     * Destinations whose latest XCM version we would like to know. Duplicates not allowed, and
     * the `u32` counter is the number of times that a send to the destination has been attempted,
     * which is used as a prioritization.
     *
     * @param {Callback<Array<[XcmVersionedMultiLocation, number]>>=} callback
     **/
    versionDiscoveryQueue: GenericStorageQuery<() => Array<[XcmVersionedMultiLocation, number]>>;

    /**
     * The current migration's stage, if any.
     *
     * @param {Callback<PalletXcmVersionMigrationStage | undefined>=} callback
     **/
    currentMigration: GenericStorageQuery<() => PalletXcmVersionMigrationStage | undefined>;

    /**
     * Fungible assets which we know are locked on a remote chain.
     *
     * @param {[number, AccountId20Like, XcmVersionedAssetId]} arg
     * @param {Callback<PalletXcmRemoteLockedFungibleRecord | undefined>=} callback
     **/
    remoteLockedFungibles: GenericStorageQuery<
      (arg: [number, AccountId20Like, XcmVersionedAssetId]) => PalletXcmRemoteLockedFungibleRecord | undefined
    >;

    /**
     * Fungible assets which we know are locked on this chain.
     *
     * @param {AccountId20Like} arg
     * @param {Callback<Array<[bigint, XcmVersionedMultiLocation]> | undefined>=} callback
     **/
    lockedFungibles: GenericStorageQuery<
      (arg: AccountId20Like) => Array<[bigint, XcmVersionedMultiLocation]> | undefined
    >;

    /**
     * Global suspension state of the XCM executor.
     *
     * @param {Callback<boolean>=} callback
     **/
    xcmExecutionSuspended: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Assets`'s storage queries
   **/
  assets: {
    /**
     * Details of an asset.
     *
     * @param {bigint} arg
     * @param {Callback<PalletAssetsAssetDetails | undefined>=} callback
     **/
    asset: GenericStorageQuery<(arg: bigint) => PalletAssetsAssetDetails | undefined>;

    /**
     * The holdings of a specific account for a specific asset.
     *
     * @param {[bigint, AccountId20Like]} arg
     * @param {Callback<PalletAssetsAssetAccount | undefined>=} callback
     **/
    account: GenericStorageQuery<(arg: [bigint, AccountId20Like]) => PalletAssetsAssetAccount | undefined>;

    /**
     * Approved balance transfers. First balance is the amount approved for transfer. Second
     * is the amount of `T::Currency` reserved for storing this.
     * First key is the asset ID, second key is the owner and third key is the delegate.
     *
     * @param {[bigint, AccountId20Like, AccountId20Like]} arg
     * @param {Callback<PalletAssetsApproval | undefined>=} callback
     **/
    approvals: GenericStorageQuery<
      (arg: [bigint, AccountId20Like, AccountId20Like]) => PalletAssetsApproval | undefined
    >;

    /**
     * Metadata of an asset.
     *
     * @param {bigint} arg
     * @param {Callback<PalletAssetsAssetMetadata>=} callback
     **/
    metadata: GenericStorageQuery<(arg: bigint) => PalletAssetsAssetMetadata>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `AssetManager`'s storage queries
   **/
  assetManager: {
    /**
     * Mapping from an asset id to asset type.
     * This is mostly used when receiving transaction specifying an asset directly,
     * like transferring an asset from this chain to another.
     *
     * @param {bigint} arg
     * @param {Callback<MoonbeamRuntimeXcmConfigAssetType | undefined>=} callback
     **/
    assetIdType: GenericStorageQuery<(arg: bigint) => MoonbeamRuntimeXcmConfigAssetType | undefined>;

    /**
     * Reverse mapping of AssetIdType. Mapping from an asset type to an asset id.
     * This is mostly used when receiving a multilocation XCM message to retrieve
     * the corresponding asset in which tokens should me minted.
     *
     * @param {MoonbeamRuntimeXcmConfigAssetType} arg
     * @param {Callback<bigint | undefined>=} callback
     **/
    assetTypeId: GenericStorageQuery<(arg: MoonbeamRuntimeXcmConfigAssetType) => bigint | undefined>;

    /**
     * Stores the units per second for local execution for a AssetType.
     * This is used to know how to charge for XCM execution in a particular
     * asset
     * Not all assets might contain units per second, hence the different storage
     *
     * @param {MoonbeamRuntimeXcmConfigAssetType} arg
     * @param {Callback<bigint | undefined>=} callback
     **/
    assetTypeUnitsPerSecond: GenericStorageQuery<(arg: MoonbeamRuntimeXcmConfigAssetType) => bigint | undefined>;

    /**
     * Stores the counter of the number of local assets that have been
     * created so far
     * This value can be used to salt the creation of an assetId, e.g.,
     * by hashing it. This is particularly useful for cases like moonbeam
     * where letting users choose their assetId would result in collision
     * in the evm side.
     *
     * @param {Callback<bigint>=} callback
     **/
    localAssetCounter: GenericStorageQuery<() => bigint>;

    /**
     * Local asset deposits, a mapping from assetId to a struct
     * holding the creator (from which the deposit was reserved) and
     * the deposit amount
     *
     * @param {bigint} arg
     * @param {Callback<PalletAssetManagerAssetInfo | undefined>=} callback
     **/
    localAssetDeposit: GenericStorageQuery<(arg: bigint) => PalletAssetManagerAssetInfo | undefined>;

    /**
     *
     * @param {Callback<Array<MoonbeamRuntimeXcmConfigAssetType>>=} callback
     **/
    supportedFeePaymentAssets: GenericStorageQuery<() => Array<MoonbeamRuntimeXcmConfigAssetType>>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `XTokens`'s storage queries
   **/
  xTokens: {
    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `XcmTransactor`'s storage queries
   **/
  xcmTransactor: {
    /**
     * Since we are using pallet-utility for account derivation (through AsDerivative),
     * we need to provide an index for the account derivation. This storage item stores the index
     * assigned for a given local account. These indices are usable as derivative in the relay chain
     *
     * @param {number} arg
     * @param {Callback<AccountId20 | undefined>=} callback
     **/
    indexToAccount: GenericStorageQuery<(arg: number) => AccountId20 | undefined>;

    /**
     * Stores the transact info of a MultiLocation. This defines how much extra weight we need to
     * add when we want to transact in the destination chain and maximum amount of weight allowed
     * by the destination chain
     *
     * @param {StagingXcmV3MultilocationMultiLocation} arg
     * @param {Callback<PalletXcmTransactorRemoteTransactInfoWithMaxWeight | undefined>=} callback
     **/
    transactInfoWithWeightLimit: GenericStorageQuery<
      (arg: StagingXcmV3MultilocationMultiLocation) => PalletXcmTransactorRemoteTransactInfoWithMaxWeight | undefined
    >;

    /**
     * Stores the fee per second for an asset in its reserve chain. This allows us to convert
     * from weight to fee
     *
     * @param {StagingXcmV3MultilocationMultiLocation} arg
     * @param {Callback<bigint | undefined>=} callback
     **/
    destinationAssetFeePerSecond: GenericStorageQuery<
      (arg: StagingXcmV3MultilocationMultiLocation) => bigint | undefined
    >;

    /**
     * Stores the indices of relay chain pallets
     *
     * @param {Callback<PalletXcmTransactorRelayIndicesRelayChainIndices>=} callback
     **/
    relayIndices: GenericStorageQuery<() => PalletXcmTransactorRelayIndicesRelayChainIndices>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `LocalAssets`'s storage queries
   **/
  localAssets: {
    /**
     * Details of an asset.
     *
     * @param {bigint} arg
     * @param {Callback<PalletAssetsAssetDetails | undefined>=} callback
     **/
    asset: GenericStorageQuery<(arg: bigint) => PalletAssetsAssetDetails | undefined>;

    /**
     * The holdings of a specific account for a specific asset.
     *
     * @param {[bigint, AccountId20Like]} arg
     * @param {Callback<PalletAssetsAssetAccount | undefined>=} callback
     **/
    account: GenericStorageQuery<(arg: [bigint, AccountId20Like]) => PalletAssetsAssetAccount | undefined>;

    /**
     * Approved balance transfers. First balance is the amount approved for transfer. Second
     * is the amount of `T::Currency` reserved for storing this.
     * First key is the asset ID, second key is the owner and third key is the delegate.
     *
     * @param {[bigint, AccountId20Like, AccountId20Like]} arg
     * @param {Callback<PalletAssetsApproval | undefined>=} callback
     **/
    approvals: GenericStorageQuery<
      (arg: [bigint, AccountId20Like, AccountId20Like]) => PalletAssetsApproval | undefined
    >;

    /**
     * Metadata of an asset.
     *
     * @param {bigint} arg
     * @param {Callback<PalletAssetsAssetMetadata>=} callback
     **/
    metadata: GenericStorageQuery<(arg: bigint) => PalletAssetsAssetMetadata>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `EthereumXcm`'s storage queries
   **/
  ethereumXcm: {
    /**
     * Global nonce used for building Ethereum transaction payload.
     *
     * @param {Callback<U256>=} callback
     **/
    nonce: GenericStorageQuery<() => U256>;

    /**
     * Whether or not Ethereum-XCM is suspended from executing
     *
     * @param {Callback<boolean>=} callback
     **/
    ethereumXcmSuspended: GenericStorageQuery<() => boolean>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
  /**
   * Pallet `Randomness`'s storage queries
   **/
  randomness: {
    /**
     * Randomness requests not yet fulfilled or purged
     *
     * @param {bigint} arg
     * @param {Callback<PalletRandomnessRequestState | undefined>=} callback
     **/
    requests: GenericStorageQuery<(arg: bigint) => PalletRandomnessRequestState | undefined>;

    /**
     * Number of randomness requests made so far, used to generate the next request's uid
     *
     * @param {Callback<bigint>=} callback
     **/
    requestCount: GenericStorageQuery<() => bigint>;

    /**
     * Current local per-block VRF randomness
     * Set in `on_initialize`
     *
     * @param {Callback<H256 | undefined>=} callback
     **/
    localVrfOutput: GenericStorageQuery<() => H256 | undefined>;

    /**
     * Relay epoch
     *
     * @param {Callback<bigint>=} callback
     **/
    relayEpoch: GenericStorageQuery<() => bigint>;

    /**
     * Ensures the mandatory inherent was included in the block
     *
     * @param {Callback<[] | undefined>=} callback
     **/
    inherentIncluded: GenericStorageQuery<() => [] | undefined>;

    /**
     * Records whether this is the first block (genesis or runtime upgrade)
     *
     * @param {Callback<[] | undefined>=} callback
     **/
    notFirstBlock: GenericStorageQuery<() => [] | undefined>;

    /**
     * Snapshot of randomness to fulfill all requests that are for the same raw randomness
     * Removed once $value.request_count == 0
     *
     * @param {PalletRandomnessRequestType} arg
     * @param {Callback<PalletRandomnessRandomnessResult | undefined>=} callback
     **/
    randomnessResults: GenericStorageQuery<
      (arg: PalletRandomnessRequestType) => PalletRandomnessRandomnessResult | undefined
    >;

    /**
     * Previous local per-block VRF randomness
     * Set in `on_finalize` of last block
     *
     * @param {Callback<H256>=} callback
     **/
    previousLocalVrfOutput: GenericStorageQuery<() => H256>;

    /**
     * Generic pallet storage query
     **/
    [storage: string]: GenericStorageQuery;
  };
}
