// Generated by dedot cli

import type { AccountId32Like, BytesLike, Result } from 'dedot/codecs';
import type {
  ContractCallOptions,
  ContractCallResult,
  GenericContractCallResult,
  GenericContractQuery,
  GenericContractQueryCall,
  MetadataType,
} from 'dedot/contracts';
import type { Psp22ErrorsPsp22Error } from './types.js';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x162df8c2
   **/
  psp22TotalSupply: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} owner
   * @param {ContractCallOptions} options
   *
   * @selector 0x6568382f
   **/
  psp22BalanceOf: GenericContractQueryCall<
    (
      owner: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} owner
   * @param {AccountId32Like} spender
   * @param {ContractCallOptions} options
   *
   * @selector 0x4d47d921
   **/
  psp22Allowance: GenericContractQueryCall<
    (
      owner: AccountId32Like,
      spender: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} to
   * @param {bigint} value
   * @param {BytesLike} data
   * @param {ContractCallOptions} options
   *
   * @selector 0xdb20f9f5
   **/
  psp22Transfer: GenericContractQueryCall<
    (
      to: AccountId32Like,
      value: bigint,
      data: BytesLike,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Psp22ErrorsPsp22Error>, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} from
   * @param {AccountId32Like} to
   * @param {bigint} value
   * @param {BytesLike} data
   * @param {ContractCallOptions} options
   *
   * @selector 0x54b3c76e
   **/
  psp22TransferFrom: GenericContractQueryCall<
    (
      from: AccountId32Like,
      to: AccountId32Like,
      value: bigint,
      data: BytesLike,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Psp22ErrorsPsp22Error>, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} spender
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0xb20f1bbd
   **/
  psp22Approve: GenericContractQueryCall<
    (
      spender: AccountId32Like,
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Psp22ErrorsPsp22Error>, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} spender
   * @param {bigint} deltaValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x96d6b57a
   **/
  psp22IncreaseAllowance: GenericContractQueryCall<
    (
      spender: AccountId32Like,
      deltaValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Psp22ErrorsPsp22Error>, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {AccountId32Like} spender
   * @param {bigint} deltaValue
   * @param {ContractCallOptions} options
   *
   * @selector 0xfecb57d5
   **/
  psp22DecreaseAllowance: GenericContractQueryCall<
    (
      spender: AccountId32Like,
      deltaValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Psp22ErrorsPsp22Error>, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x3d261bd4
   **/
  psp22MetadataTokenName: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<string | undefined, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x34205be5
   **/
  psp22MetadataTokenSymbol: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<string | undefined, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7271b782
   **/
  psp22MetadataTokenDecimals: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {bigint} value
   * @param {ContractCallOptions} options
   *
   * @selector 0xfc3c75d4
   **/
  psp22MintableMint: GenericContractQueryCall<
    (
      value: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Psp22ErrorsPsp22Error>, ContractCallResult>>,
    Type
  >;
}
