// Generated by dedot cli

import type { AccountId32 } from 'dedot/codecs';

export type InkStorageLazy = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Flipper = {
  value: { get(): Promise<boolean | undefined> };
  owner: { get(): Promise<AccountId32 | undefined> };
};

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type InkEnvNoChainExtension = null;
