// Generated by dedot cli

import type {
  ConstructorCallOptions,
  ContractInstantiateResult,
  GenericConstructorCallResult,
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorQuery<Type extends MetadataType> extends GenericConstructorQuery<Type> {
  /**
   * @param {boolean} init_value
   * @param {ConstructorCallOptions} options
   **/
  new: GenericConstructorQueryCall<
    (
      init_value: boolean,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
