// Generated by dedot cli

import type {
  ContractCallOptions,
  ContractCallResult,
  GenericContractCallResult,
  GenericContractQuery,
  GenericContractQueryCall,
  MetadataType,
} from 'dedot/contracts';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * @param {ContractCallOptions} options
   **/
  flip: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  get: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  throwErrorWithNamedParams: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  throwErrorWithParams: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  throwUnitError: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;
}
