// Generated by dedot cli

import type { GenericChainViewFunctions, RpcVersion } from '@dedot/types';

export interface ChainViewFunctions<Rv extends RpcVersion> extends GenericChainViewFunctions<Rv> {}
