// Generated by dedot cli

import type {
  ConstructorTxOptions,
  GenericConstructorTx,
  GenericConstructorTxCall,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
  SolGenericContractApi,
} from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends SolGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<ChainApi, Type> {
  /**
   * @param {bigint} total_supply
   * @param {ConstructorTxOptions} options
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      total_supply: bigint,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;
}
