// Generated by dedot cli
import type {
  ConstructorCallOptions,
  ContractInstantiateResult,
  GenericConstructorCallResult,
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  MetadataType,
} from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericConstructorQuery<ChainApi, Type> {
  /**
   *
   * @param {bigint} supply
   * @param {string | undefined} name
   * @param {string | undefined} symbol
   * @param {number} decimals
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      supply: bigint,
      name: string | undefined,
      symbol: string | undefined,
      decimals: number,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
