// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Psp22v6Token = {
  data: Psp22v6DataPsp22Data;
  name?: string | undefined;
  symbol?: string | undefined;
  decimals: number;
};

export type Psp22v6DataPsp22Data = {
  totalSupply: bigint;
  balances: { get(arg: H160): Promise<bigint | undefined> };
  allowances: { get(arg: [H160, H160]): Promise<bigint | undefined> };
};

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type Psp22v6ErrorsPsp22Error =
  | { type: 'Custom'; value: string }
  | { type: 'InsufficientBalance' }
  | { type: 'InsufficientAllowance' }
  | { type: 'ZeroRecipientAddress' }
  | { type: 'ZeroSenderAddress' }
  | { type: 'SafeTransferCheckFailed'; value: string };

export type InkPrimitivesNoChainExtension = null;
