// Generated by dedot cli

import type {
  ConstructorCallOptions,
  ContractInstantiateResult,
  GenericConstructorCallResult,
  SolGenericConstructorQuery,
  SolGenericConstructorQueryCall,
} from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi> extends SolGenericConstructorQuery<ChainApi> {
  /**
   * @param {boolean} initValue
   * @param {ConstructorCallOptions} options
   **/
  initialize: SolGenericConstructorQueryCall<
    ChainApi,
    (
      initValue: boolean,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>>
  >;
}
