// Generated by dedot cli

import type {
  ContractCallOptions,
  ContractCallResult,
  GenericContractCallResult,
  GenericContractQuery,
  GenericContractQueryCall,
  MetadataType,
} from 'dedot/contracts';
import type { FlipWithStructFlipRequestInput, FlipWithStructOutput } from './types.js';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * @param {ContractCallOptions} options
   **/
  flip: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult>>,
    Type
  >;

  /**
   * @param {FlipWithStructFlipRequestInput} flip_request
   * @param {ContractCallOptions} options
   **/
  flipWithStruct: GenericContractQueryCall<
    (
      flip_request: FlipWithStructFlipRequestInput,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<FlipWithStructOutput, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  get: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  throwErrorWithNamedParams: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  throwErrorWithParams: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  throwUnitError: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;
}
