// Generated by @delightfuldot/codegen

import type { GenericChainErrors, GenericModuleError } from '@delightfuldot/types';

export interface ChainErrors extends GenericChainErrors {
  system: {
    /**
     * The name of specification does not match between the current runtime
     * and the new runtime.
     **/
    InvalidSpecName: GenericModuleError;

    /**
     * The specification version is not allowed to decrease between the current runtime
     * and the new runtime.
     **/
    SpecVersionNeedsToIncrease: GenericModuleError;

    /**
     * Failed to extract the runtime version from the new runtime.
     *
     * Either calling `Core_version` or decoding `RuntimeVersion` failed.
     **/
    FailedToExtractRuntimeVersion: GenericModuleError;

    /**
     * Suicide called when the account has non-default composite data.
     **/
    NonDefaultComposite: GenericModuleError;

    /**
     * There is a non-zero reference count preventing the account from being purged.
     **/
    NonZeroRefCount: GenericModuleError;

    /**
     * The origin filter prevent the call to be dispatched.
     **/
    CallFiltered: GenericModuleError;
  };
  utility: {
    /**
     * Too many calls batched.
     **/
    TooManyCalls: GenericModuleError;
  };
  babe: {
    /**
     * An equivocation proof provided as part of an equivocation report is invalid.
     **/
    InvalidEquivocationProof: GenericModuleError;

    /**
     * A key ownership proof provided as part of an equivocation report is invalid.
     **/
    InvalidKeyOwnershipProof: GenericModuleError;

    /**
     * A given equivocation report is valid but already previously reported.
     **/
    DuplicateOffenceReport: GenericModuleError;

    /**
     * Submitted configuration is invalid.
     **/
    InvalidConfiguration: GenericModuleError;
  };
  indices: {
    /**
     * The index was not already assigned.
     **/
    NotAssigned: GenericModuleError;

    /**
     * The index is assigned to another account.
     **/
    NotOwner: GenericModuleError;

    /**
     * The index was not available.
     **/
    InUse: GenericModuleError;

    /**
     * The source and destination accounts are identical.
     **/
    NotTransfer: GenericModuleError;

    /**
     * The index is permanent and may not be freed/changed.
     **/
    Permanent: GenericModuleError;
  };
  balances: {
    /**
     * Vesting balance too high to send value.
     **/
    VestingBalance: GenericModuleError;

    /**
     * Account liquidity restrictions prevent withdrawal.
     **/
    LiquidityRestrictions: GenericModuleError;

    /**
     * Balance too low to send value.
     **/
    InsufficientBalance: GenericModuleError;

    /**
     * Value too low to create account due to existential deposit.
     **/
    ExistentialDeposit: GenericModuleError;

    /**
     * Transfer/payment would kill account.
     **/
    Expendability: GenericModuleError;

    /**
     * A vesting schedule already exists for this account.
     **/
    ExistingVestingSchedule: GenericModuleError;

    /**
     * Beneficiary account must pre-exist.
     **/
    DeadAccount: GenericModuleError;

    /**
     * Number of named reserves exceed `MaxReserves`.
     **/
    TooManyReserves: GenericModuleError;

    /**
     * Number of holds exceed `MaxHolds`.
     **/
    TooManyHolds: GenericModuleError;

    /**
     * Number of freezes exceed `MaxFreezes`.
     **/
    TooManyFreezes: GenericModuleError;
  };
  electionProviderMultiPhase: {
    /**
     * Submission was too early.
     **/
    PreDispatchEarlySubmission: GenericModuleError;

    /**
     * Wrong number of winners presented.
     **/
    PreDispatchWrongWinnerCount: GenericModuleError;

    /**
     * Submission was too weak, score-wise.
     **/
    PreDispatchWeakSubmission: GenericModuleError;

    /**
     * The queue was full, and the solution was not better than any of the existing ones.
     **/
    SignedQueueFull: GenericModuleError;

    /**
     * The origin failed to pay the deposit.
     **/
    SignedCannotPayDeposit: GenericModuleError;

    /**
     * Witness data to dispatchable is invalid.
     **/
    SignedInvalidWitness: GenericModuleError;

    /**
     * The signed submission consumes too much weight
     **/
    SignedTooMuchWeight: GenericModuleError;

    /**
     * OCW submitted solution for wrong round
     **/
    OcwCallWrongEra: GenericModuleError;

    /**
     * Snapshot metadata should exist but didn't.
     **/
    MissingSnapshotMetadata: GenericModuleError;

    /**
     * `Self::insert_submission` returned an invalid index.
     **/
    InvalidSubmissionIndex: GenericModuleError;

    /**
     * The call is not allowed at this point.
     **/
    CallNotAllowed: GenericModuleError;

    /**
     * The fallback failed
     **/
    FallbackFailed: GenericModuleError;

    /**
     * Some bound not met
     **/
    BoundNotMet: GenericModuleError;

    /**
     * Submitted solution has too many winners
     **/
    TooManyWinners: GenericModuleError;
  };
  staking: {
    /**
     * Not a controller account.
     **/
    NotController: GenericModuleError;

    /**
     * Not a stash account.
     **/
    NotStash: GenericModuleError;

    /**
     * Stash is already bonded.
     **/
    AlreadyBonded: GenericModuleError;

    /**
     * Controller is already paired.
     **/
    AlreadyPaired: GenericModuleError;

    /**
     * Targets cannot be empty.
     **/
    EmptyTargets: GenericModuleError;

    /**
     * Duplicate index.
     **/
    DuplicateIndex: GenericModuleError;

    /**
     * Slash record index out of bounds.
     **/
    InvalidSlashIndex: GenericModuleError;

    /**
     * Cannot have a validator or nominator role, with value less than the minimum defined by
     * governance (see `MinValidatorBond` and `MinNominatorBond`). If unbonding is the
     * intention, `chill` first to remove one's role as validator/nominator.
     **/
    InsufficientBond: GenericModuleError;

    /**
     * Can not schedule more unlock chunks.
     **/
    NoMoreChunks: GenericModuleError;

    /**
     * Can not rebond without unlocking chunks.
     **/
    NoUnlockChunk: GenericModuleError;

    /**
     * Attempting to target a stash that still has funds.
     **/
    FundedTarget: GenericModuleError;

    /**
     * Invalid era to reward.
     **/
    InvalidEraToReward: GenericModuleError;

    /**
     * Invalid number of nominations.
     **/
    InvalidNumberOfNominations: GenericModuleError;

    /**
     * Items are not sorted and unique.
     **/
    NotSortedAndUnique: GenericModuleError;

    /**
     * Rewards for this era have already been claimed for this validator.
     **/
    AlreadyClaimed: GenericModuleError;

    /**
     * Incorrect previous history depth input provided.
     **/
    IncorrectHistoryDepth: GenericModuleError;

    /**
     * Incorrect number of slashing spans provided.
     **/
    IncorrectSlashingSpans: GenericModuleError;

    /**
     * Internal state has become somehow corrupted and the operation cannot continue.
     **/
    BadState: GenericModuleError;

    /**
     * Too many nomination targets supplied.
     **/
    TooManyTargets: GenericModuleError;

    /**
     * A nomination target was supplied that was blocked or otherwise not a validator.
     **/
    BadTarget: GenericModuleError;

    /**
     * The user has enough bond and thus cannot be chilled forcefully by an external person.
     **/
    CannotChillOther: GenericModuleError;

    /**
     * There are too many nominators in the system. Governance needs to adjust the staking
     * settings to keep things safe for the runtime.
     **/
    TooManyNominators: GenericModuleError;

    /**
     * There are too many validator candidates in the system. Governance needs to adjust the
     * staking settings to keep things safe for the runtime.
     **/
    TooManyValidators: GenericModuleError;

    /**
     * Commission is too low. Must be at least `MinCommission`.
     **/
    CommissionTooLow: GenericModuleError;

    /**
     * Some bound is not met.
     **/
    BoundNotMet: GenericModuleError;
  };
  session: {
    /**
     * Invalid ownership proof.
     **/
    InvalidProof: GenericModuleError;

    /**
     * No associated validator ID for account.
     **/
    NoAssociatedValidatorId: GenericModuleError;

    /**
     * Registered duplicate key.
     **/
    DuplicatedKey: GenericModuleError;

    /**
     * No keys are associated with this account.
     **/
    NoKeys: GenericModuleError;

    /**
     * Key setting account is not live, so it's impossible to associate keys.
     **/
    NoAccount: GenericModuleError;
  };
  democracy: {
    /**
     * Value too low
     **/
    ValueLow: GenericModuleError;

    /**
     * Proposal does not exist
     **/
    ProposalMissing: GenericModuleError;

    /**
     * Cannot cancel the same proposal twice
     **/
    AlreadyCanceled: GenericModuleError;

    /**
     * Proposal already made
     **/
    DuplicateProposal: GenericModuleError;

    /**
     * Proposal still blacklisted
     **/
    ProposalBlacklisted: GenericModuleError;

    /**
     * Next external proposal not simple majority
     **/
    NotSimpleMajority: GenericModuleError;

    /**
     * Invalid hash
     **/
    InvalidHash: GenericModuleError;

    /**
     * No external proposal
     **/
    NoProposal: GenericModuleError;

    /**
     * Identity may not veto a proposal twice
     **/
    AlreadyVetoed: GenericModuleError;

    /**
     * Vote given for invalid referendum
     **/
    ReferendumInvalid: GenericModuleError;

    /**
     * No proposals waiting
     **/
    NoneWaiting: GenericModuleError;

    /**
     * The given account did not vote on the referendum.
     **/
    NotVoter: GenericModuleError;

    /**
     * The actor has no permission to conduct the action.
     **/
    NoPermission: GenericModuleError;

    /**
     * The account is already delegating.
     **/
    AlreadyDelegating: GenericModuleError;

    /**
     * Too high a balance was provided that the account cannot afford.
     **/
    InsufficientFunds: GenericModuleError;

    /**
     * The account is not currently delegating.
     **/
    NotDelegating: GenericModuleError;

    /**
     * The account currently has votes attached to it and the operation cannot succeed until
     * these are removed, either through `unvote` or `reap_vote`.
     **/
    VotesExist: GenericModuleError;

    /**
     * The instant referendum origin is currently disallowed.
     **/
    InstantNotAllowed: GenericModuleError;

    /**
     * Delegation to oneself makes no sense.
     **/
    Nonsense: GenericModuleError;

    /**
     * Invalid upper bound.
     **/
    WrongUpperBound: GenericModuleError;

    /**
     * Maximum number of votes reached.
     **/
    MaxVotesReached: GenericModuleError;

    /**
     * Maximum number of items reached.
     **/
    TooMany: GenericModuleError;

    /**
     * Voting period too low
     **/
    VotingPeriodLow: GenericModuleError;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericModuleError;
  };
  council: {
    /**
     * Account is not a member
     **/
    NotMember: GenericModuleError;

    /**
     * Duplicate proposals not allowed
     **/
    DuplicateProposal: GenericModuleError;

    /**
     * Proposal must exist
     **/
    ProposalMissing: GenericModuleError;

    /**
     * Mismatched index
     **/
    WrongIndex: GenericModuleError;

    /**
     * Duplicate vote ignored
     **/
    DuplicateVote: GenericModuleError;

    /**
     * Members are already initialized!
     **/
    AlreadyInitialized: GenericModuleError;

    /**
     * The close call was made too early, before the end of the voting.
     **/
    TooEarly: GenericModuleError;

    /**
     * There can only be a maximum of `MaxProposals` active proposals.
     **/
    TooManyProposals: GenericModuleError;

    /**
     * The given weight bound for the proposal was too low.
     **/
    WrongProposalWeight: GenericModuleError;

    /**
     * The given length bound for the proposal was too low.
     **/
    WrongProposalLength: GenericModuleError;

    /**
     * Prime account is not a member
     **/
    PrimeAccountNotMember: GenericModuleError;
  };
  technicalCommittee: {
    /**
     * Account is not a member
     **/
    NotMember: GenericModuleError;

    /**
     * Duplicate proposals not allowed
     **/
    DuplicateProposal: GenericModuleError;

    /**
     * Proposal must exist
     **/
    ProposalMissing: GenericModuleError;

    /**
     * Mismatched index
     **/
    WrongIndex: GenericModuleError;

    /**
     * Duplicate vote ignored
     **/
    DuplicateVote: GenericModuleError;

    /**
     * Members are already initialized!
     **/
    AlreadyInitialized: GenericModuleError;

    /**
     * The close call was made too early, before the end of the voting.
     **/
    TooEarly: GenericModuleError;

    /**
     * There can only be a maximum of `MaxProposals` active proposals.
     **/
    TooManyProposals: GenericModuleError;

    /**
     * The given weight bound for the proposal was too low.
     **/
    WrongProposalWeight: GenericModuleError;

    /**
     * The given length bound for the proposal was too low.
     **/
    WrongProposalLength: GenericModuleError;

    /**
     * Prime account is not a member
     **/
    PrimeAccountNotMember: GenericModuleError;
  };
  elections: {
    /**
     * Cannot vote when no candidates or members exist.
     **/
    UnableToVote: GenericModuleError;

    /**
     * Must vote for at least one candidate.
     **/
    NoVotes: GenericModuleError;

    /**
     * Cannot vote more than candidates.
     **/
    TooManyVotes: GenericModuleError;

    /**
     * Cannot vote more than maximum allowed.
     **/
    MaximumVotesExceeded: GenericModuleError;

    /**
     * Cannot vote with stake less than minimum balance.
     **/
    LowBalance: GenericModuleError;

    /**
     * Voter can not pay voting bond.
     **/
    UnableToPayBond: GenericModuleError;

    /**
     * Must be a voter.
     **/
    MustBeVoter: GenericModuleError;

    /**
     * Duplicated candidate submission.
     **/
    DuplicatedCandidate: GenericModuleError;

    /**
     * Too many candidates have been created.
     **/
    TooManyCandidates: GenericModuleError;

    /**
     * Member cannot re-submit candidacy.
     **/
    MemberSubmit: GenericModuleError;

    /**
     * Runner cannot re-submit candidacy.
     **/
    RunnerUpSubmit: GenericModuleError;

    /**
     * Candidate does not have enough funds.
     **/
    InsufficientCandidateFunds: GenericModuleError;

    /**
     * Not a member.
     **/
    NotMember: GenericModuleError;

    /**
     * The provided count of number of candidates is incorrect.
     **/
    InvalidWitnessData: GenericModuleError;

    /**
     * The provided count of number of votes is incorrect.
     **/
    InvalidVoteCount: GenericModuleError;

    /**
     * The renouncing origin presented a wrong `Renouncing` parameter.
     **/
    InvalidRenouncing: GenericModuleError;

    /**
     * Prediction regarding replacement after member removal is wrong.
     **/
    InvalidReplacement: GenericModuleError;
  };
  technicalMembership: {
    /**
     * Already a member.
     **/
    AlreadyMember: GenericModuleError;

    /**
     * Not a member.
     **/
    NotMember: GenericModuleError;

    /**
     * Too many members.
     **/
    TooManyMembers: GenericModuleError;
  };
  grandpa: {
    /**
     * Attempt to signal GRANDPA pause when the authority set isn't live
     * (either paused or already pending pause).
     **/
    PauseFailed: GenericModuleError;

    /**
     * Attempt to signal GRANDPA resume when the authority set isn't paused
     * (either live or already pending resume).
     **/
    ResumeFailed: GenericModuleError;

    /**
     * Attempt to signal GRANDPA change with one already pending.
     **/
    ChangePending: GenericModuleError;

    /**
     * Cannot signal forced change so soon after last.
     **/
    TooSoon: GenericModuleError;

    /**
     * A key ownership proof provided as part of an equivocation report is invalid.
     **/
    InvalidKeyOwnershipProof: GenericModuleError;

    /**
     * An equivocation proof provided as part of an equivocation report is invalid.
     **/
    InvalidEquivocationProof: GenericModuleError;

    /**
     * A given equivocation report is valid but already previously reported.
     **/
    DuplicateOffenceReport: GenericModuleError;
  };
  treasury: {
    /**
     * Proposer's balance is too low.
     **/
    InsufficientProposersBalance: GenericModuleError;

    /**
     * No proposal or bounty at that index.
     **/
    InvalidIndex: GenericModuleError;

    /**
     * Too many approvals in the queue.
     **/
    TooManyApprovals: GenericModuleError;

    /**
     * The spend origin is valid but the amount it is allowed to spend is lower than the
     * amount to be spent.
     **/
    InsufficientPermission: GenericModuleError;

    /**
     * Proposal has not been approved.
     **/
    ProposalNotApproved: GenericModuleError;
  };
  assetRate: {
    /**
     * The given asset ID is unknown.
     **/
    UnknownAssetKind: GenericModuleError;

    /**
     * The given asset ID already has an assigned conversion rate and cannot be re-created.
     **/
    AlreadyExists: GenericModuleError;
  };
  contracts: {
    /**
     * Invalid schedule supplied, e.g. with zero weight of a basic operation.
     **/
    InvalidSchedule: GenericModuleError;

    /**
     * Invalid combination of flags supplied to `seal_call` or `seal_delegate_call`.
     **/
    InvalidCallFlags: GenericModuleError;

    /**
     * The executed contract exhausted its gas limit.
     **/
    OutOfGas: GenericModuleError;

    /**
     * The output buffer supplied to a contract API call was too small.
     **/
    OutputBufferTooSmall: GenericModuleError;

    /**
     * Performing the requested transfer failed. Probably because there isn't enough
     * free balance in the sender's account.
     **/
    TransferFailed: GenericModuleError;

    /**
     * Performing a call was denied because the calling depth reached the limit
     * of what is specified in the schedule.
     **/
    MaxCallDepthReached: GenericModuleError;

    /**
     * No contract was found at the specified address.
     **/
    ContractNotFound: GenericModuleError;

    /**
     * The code supplied to `instantiate_with_code` exceeds the limit specified in the
     * current schedule.
     **/
    CodeTooLarge: GenericModuleError;

    /**
     * No code could be found at the supplied code hash.
     **/
    CodeNotFound: GenericModuleError;

    /**
     * No code info could be found at the supplied code hash.
     **/
    CodeInfoNotFound: GenericModuleError;

    /**
     * A buffer outside of sandbox memory was passed to a contract API function.
     **/
    OutOfBounds: GenericModuleError;

    /**
     * Input passed to a contract API function failed to decode as expected type.
     **/
    DecodingFailed: GenericModuleError;

    /**
     * Contract trapped during execution.
     **/
    ContractTrapped: GenericModuleError;

    /**
     * The size defined in `T::MaxValueSize` was exceeded.
     **/
    ValueTooLarge: GenericModuleError;

    /**
     * Termination of a contract is not allowed while the contract is already
     * on the call stack. Can be triggered by `seal_terminate`.
     **/
    TerminatedWhileReentrant: GenericModuleError;

    /**
     * `seal_call` forwarded this contracts input. It therefore is no longer available.
     **/
    InputForwarded: GenericModuleError;

    /**
     * The subject passed to `seal_random` exceeds the limit.
     **/
    RandomSubjectTooLong: GenericModuleError;

    /**
     * The amount of topics passed to `seal_deposit_events` exceeds the limit.
     **/
    TooManyTopics: GenericModuleError;

    /**
     * The chain does not provide a chain extension. Calling the chain extension results
     * in this error. Note that this usually shouldn't happen as deploying such contracts
     * is rejected.
     **/
    NoChainExtension: GenericModuleError;

    /**
     * A contract with the same AccountId already exists.
     **/
    DuplicateContract: GenericModuleError;

    /**
     * A contract self destructed in its constructor.
     *
     * This can be triggered by a call to `seal_terminate`.
     **/
    TerminatedInConstructor: GenericModuleError;

    /**
     * A call tried to invoke a contract that is flagged as non-reentrant.
     * The only other cause is that a call from a contract into the runtime tried to call back
     * into `pallet-contracts`. This would make the whole pallet reentrant with regard to
     * contract code execution which is not supported.
     **/
    ReentranceDenied: GenericModuleError;

    /**
     * Origin doesn't have enough balance to pay the required storage deposits.
     **/
    StorageDepositNotEnoughFunds: GenericModuleError;

    /**
     * More storage was created than allowed by the storage deposit limit.
     **/
    StorageDepositLimitExhausted: GenericModuleError;

    /**
     * Code removal was denied because the code is still in use by at least one contract.
     **/
    CodeInUse: GenericModuleError;

    /**
     * The contract ran to completion but decided to revert its storage changes.
     * Please note that this error is only returned from extrinsics. When called directly
     * or via RPC an `Ok` will be returned. In this case the caller needs to inspect the flags
     * to determine whether a reversion has taken place.
     **/
    ContractReverted: GenericModuleError;

    /**
     * The contract's code was found to be invalid during validation.
     *
     * The most likely cause of this is that an API was used which is not supported by the
     * node. This happens if an older node is used with a new version of ink!. Try updating
     * your node to the newest available version.
     *
     * A more detailed error can be found on the node console if debug messages are enabled
     * by supplying `-lruntime::contracts=debug`.
     **/
    CodeRejected: GenericModuleError;

    /**
     * An indetermistic code was used in a context where this is not permitted.
     **/
    Indeterministic: GenericModuleError;

    /**
     * A pending migration needs to complete before the extrinsic can be called.
     **/
    MigrationInProgress: GenericModuleError;

    /**
     * Migrate dispatch call was attempted but no migration was performed.
     **/
    NoMigrationPerformed: GenericModuleError;

    /**
     * The contract has reached its maximum number of delegate dependencies.
     **/
    MaxDelegateDependenciesReached: GenericModuleError;

    /**
     * The dependency was not found in the contract's delegate dependencies.
     **/
    DelegateDependencyNotFound: GenericModuleError;

    /**
     * The contract already depends on the given delegate dependency.
     **/
    DelegateDependencyAlreadyExists: GenericModuleError;

    /**
     * Can not add a delegate dependency to the code hash of the contract itself.
     **/
    CannotAddSelfAsDelegateDependency: GenericModuleError;
  };
  sudo: {
    /**
     * Sender must be the Sudo account
     **/
    RequireSudo: GenericModuleError;
  };
  imOnline: {
    /**
     * Non existent public key.
     **/
    InvalidKey: GenericModuleError;

    /**
     * Duplicated heartbeat.
     **/
    DuplicatedHeartbeat: GenericModuleError;
  };
  identity: {
    /**
     * Too many subs-accounts.
     **/
    TooManySubAccounts: GenericModuleError;

    /**
     * Account isn't found.
     **/
    NotFound: GenericModuleError;

    /**
     * Account isn't named.
     **/
    NotNamed: GenericModuleError;

    /**
     * Empty index.
     **/
    EmptyIndex: GenericModuleError;

    /**
     * Fee is changed.
     **/
    FeeChanged: GenericModuleError;

    /**
     * No identity found.
     **/
    NoIdentity: GenericModuleError;

    /**
     * Sticky judgement.
     **/
    StickyJudgement: GenericModuleError;

    /**
     * Judgement given.
     **/
    JudgementGiven: GenericModuleError;

    /**
     * Invalid judgement.
     **/
    InvalidJudgement: GenericModuleError;

    /**
     * The index is invalid.
     **/
    InvalidIndex: GenericModuleError;

    /**
     * The target is invalid.
     **/
    InvalidTarget: GenericModuleError;

    /**
     * Too many additional fields.
     **/
    TooManyFields: GenericModuleError;

    /**
     * Maximum amount of registrars reached. Cannot add any more.
     **/
    TooManyRegistrars: GenericModuleError;

    /**
     * Account ID is already named.
     **/
    AlreadyClaimed: GenericModuleError;

    /**
     * Sender is not a sub-account.
     **/
    NotSub: GenericModuleError;

    /**
     * Sub-account isn't owned by sender.
     **/
    NotOwned: GenericModuleError;

    /**
     * The provided judgement was for a different identity.
     **/
    JudgementForDifferentIdentity: GenericModuleError;

    /**
     * Error that occurs when there is an issue paying for judgement.
     **/
    JudgementPaymentFailed: GenericModuleError;
  };
  society: {
    /**
     * User is not a member.
     **/
    NotMember: GenericModuleError;

    /**
     * User is already a member.
     **/
    AlreadyMember: GenericModuleError;

    /**
     * User is suspended.
     **/
    Suspended: GenericModuleError;

    /**
     * User is not suspended.
     **/
    NotSuspended: GenericModuleError;

    /**
     * Nothing to payout.
     **/
    NoPayout: GenericModuleError;

    /**
     * Society already founded.
     **/
    AlreadyFounded: GenericModuleError;

    /**
     * Not enough in pot to accept candidate.
     **/
    InsufficientPot: GenericModuleError;

    /**
     * Member is already vouching or banned from vouching again.
     **/
    AlreadyVouching: GenericModuleError;

    /**
     * Member is not vouching.
     **/
    NotVouchingOnBidder: GenericModuleError;

    /**
     * Cannot remove the head of the chain.
     **/
    Head: GenericModuleError;

    /**
     * Cannot remove the founder.
     **/
    Founder: GenericModuleError;

    /**
     * User has already made a bid.
     **/
    AlreadyBid: GenericModuleError;

    /**
     * User is already a candidate.
     **/
    AlreadyCandidate: GenericModuleError;

    /**
     * User is not a candidate.
     **/
    NotCandidate: GenericModuleError;

    /**
     * Too many members in the society.
     **/
    MaxMembers: GenericModuleError;

    /**
     * The caller is not the founder.
     **/
    NotFounder: GenericModuleError;

    /**
     * The caller is not the head.
     **/
    NotHead: GenericModuleError;

    /**
     * The membership cannot be claimed as the candidate was not clearly approved.
     **/
    NotApproved: GenericModuleError;

    /**
     * The candidate cannot be kicked as the candidate was not clearly rejected.
     **/
    NotRejected: GenericModuleError;

    /**
     * The candidacy cannot be dropped as the candidate was clearly approved.
     **/
    Approved: GenericModuleError;

    /**
     * The candidacy cannot be bestowed as the candidate was clearly rejected.
     **/
    Rejected: GenericModuleError;

    /**
     * The candidacy cannot be concluded as the voting is still in progress.
     **/
    InProgress: GenericModuleError;

    /**
     * The candidacy cannot be pruned until a full additional intake period has passed.
     **/
    TooEarly: GenericModuleError;

    /**
     * The skeptic already voted.
     **/
    Voted: GenericModuleError;

    /**
     * The skeptic need not vote on candidates from expired rounds.
     **/
    Expired: GenericModuleError;

    /**
     * User is not a bidder.
     **/
    NotBidder: GenericModuleError;

    /**
     * There is no defender currently.
     **/
    NoDefender: GenericModuleError;

    /**
     * Group doesn't exist.
     **/
    NotGroup: GenericModuleError;

    /**
     * The member is already elevated to this rank.
     **/
    AlreadyElevated: GenericModuleError;

    /**
     * The skeptic has already been punished for this offence.
     **/
    AlreadyPunished: GenericModuleError;

    /**
     * Funds are insufficient to pay off society debts.
     **/
    InsufficientFunds: GenericModuleError;

    /**
     * The candidate/defender has no stale votes to remove.
     **/
    NoVotes: GenericModuleError;
  };
  recovery: {
    /**
     * User is not allowed to make a call on behalf of this account
     **/
    NotAllowed: GenericModuleError;

    /**
     * Threshold must be greater than zero
     **/
    ZeroThreshold: GenericModuleError;

    /**
     * Friends list must be greater than zero and threshold
     **/
    NotEnoughFriends: GenericModuleError;

    /**
     * Friends list must be less than max friends
     **/
    MaxFriends: GenericModuleError;

    /**
     * Friends list must be sorted and free of duplicates
     **/
    NotSorted: GenericModuleError;

    /**
     * This account is not set up for recovery
     **/
    NotRecoverable: GenericModuleError;

    /**
     * This account is already set up for recovery
     **/
    AlreadyRecoverable: GenericModuleError;

    /**
     * A recovery process has already started for this account
     **/
    AlreadyStarted: GenericModuleError;

    /**
     * A recovery process has not started for this rescuer
     **/
    NotStarted: GenericModuleError;

    /**
     * This account is not a friend who can vouch
     **/
    NotFriend: GenericModuleError;

    /**
     * The friend must wait until the delay period to vouch for this recovery
     **/
    DelayPeriod: GenericModuleError;

    /**
     * This user has already vouched for this recovery
     **/
    AlreadyVouched: GenericModuleError;

    /**
     * The threshold for recovering this account has not been met
     **/
    Threshold: GenericModuleError;

    /**
     * There are still active recovery attempts that need to be closed
     **/
    StillActive: GenericModuleError;

    /**
     * This account is already set up for recovery
     **/
    AlreadyProxy: GenericModuleError;

    /**
     * Some internal state is broken.
     **/
    BadState: GenericModuleError;
  };
  vesting: {
    /**
     * The account given is not vesting.
     **/
    NotVesting: GenericModuleError;

    /**
     * The account already has `MaxVestingSchedules` count of schedules and thus
     * cannot add another one. Consider merging existing schedules in order to add another.
     **/
    AtMaxVestingSchedules: GenericModuleError;

    /**
     * Amount being transferred is too low to create a vesting schedule.
     **/
    AmountLow: GenericModuleError;

    /**
     * An index was out of bounds of the vesting schedules.
     **/
    ScheduleIndexOutOfBounds: GenericModuleError;

    /**
     * Failed to create a new schedule because some parameter was invalid.
     **/
    InvalidScheduleParams: GenericModuleError;
  };
  scheduler: {
    /**
     * Failed to schedule a call
     **/
    FailedToSchedule: GenericModuleError;

    /**
     * Cannot find the scheduled call.
     **/
    NotFound: GenericModuleError;

    /**
     * Given target block number is in the past.
     **/
    TargetBlockNumberInPast: GenericModuleError;

    /**
     * Reschedule failed because it does not change scheduled time.
     **/
    RescheduleNoChange: GenericModuleError;

    /**
     * Attempt to use a non-named function on a named task.
     **/
    Named: GenericModuleError;
  };
  glutton: {
    /**
     * The pallet was already initialized.
     *
     * Set `witness_count` to `Some` to bypass this error.
     **/
    AlreadyInitialized: GenericModuleError;

    /**
     * The limit was over [`crate::RESOURCE_HARD_LIMIT`].
     **/
    InsaneLimit: GenericModuleError;
  };
  preimage: {
    /**
     * Preimage is too large to store on-chain.
     **/
    TooBig: GenericModuleError;

    /**
     * Preimage has already been noted on-chain.
     **/
    AlreadyNoted: GenericModuleError;

    /**
     * The user is not authorized to perform this action.
     **/
    NotAuthorized: GenericModuleError;

    /**
     * The preimage cannot be removed since it has not yet been noted.
     **/
    NotNoted: GenericModuleError;

    /**
     * A preimage may not be removed when there are outstanding requests.
     **/
    Requested: GenericModuleError;

    /**
     * The preimage request cannot be removed since no outstanding requests exist.
     **/
    NotRequested: GenericModuleError;
  };
  proxy: {
    /**
     * There are too many proxies registered or too many announcements pending.
     **/
    TooMany: GenericModuleError;

    /**
     * Proxy registration not found.
     **/
    NotFound: GenericModuleError;

    /**
     * Sender is not a proxy of the account to be proxied.
     **/
    NotProxy: GenericModuleError;

    /**
     * A call which is incompatible with the proxy type's filter was attempted.
     **/
    Unproxyable: GenericModuleError;

    /**
     * Account is already a proxy.
     **/
    Duplicate: GenericModuleError;

    /**
     * Call may not be made by proxy because it may escalate its privileges.
     **/
    NoPermission: GenericModuleError;

    /**
     * Announcement, if made at all, was made too recently.
     **/
    Unannounced: GenericModuleError;

    /**
     * Cannot add self as proxy.
     **/
    NoSelfProxy: GenericModuleError;
  };
  multisig: {
    /**
     * Threshold must be 2 or greater.
     **/
    MinimumThreshold: GenericModuleError;

    /**
     * Call is already approved by this signatory.
     **/
    AlreadyApproved: GenericModuleError;

    /**
     * Call doesn't need any (more) approvals.
     **/
    NoApprovalsNeeded: GenericModuleError;

    /**
     * There are too few signatories in the list.
     **/
    TooFewSignatories: GenericModuleError;

    /**
     * There are too many signatories in the list.
     **/
    TooManySignatories: GenericModuleError;

    /**
     * The signatories were provided out of order; they should be ordered.
     **/
    SignatoriesOutOfOrder: GenericModuleError;

    /**
     * The sender was contained in the other signatories; it shouldn't be.
     **/
    SenderInSignatories: GenericModuleError;

    /**
     * Multisig operation not found when attempting to cancel.
     **/
    NotFound: GenericModuleError;

    /**
     * Only the account that originally created the multisig is able to cancel it.
     **/
    NotOwner: GenericModuleError;

    /**
     * No timepoint was given, yet the multisig operation is already underway.
     **/
    NoTimepoint: GenericModuleError;

    /**
     * A different timepoint was given to the multisig operation that is underway.
     **/
    WrongTimepoint: GenericModuleError;

    /**
     * A timepoint was given, yet no multisig operation is underway.
     **/
    UnexpectedTimepoint: GenericModuleError;

    /**
     * The maximum weight information provided was too low.
     **/
    MaxWeightTooLow: GenericModuleError;

    /**
     * The data to be stored is already stored.
     **/
    AlreadyStored: GenericModuleError;
  };
  bounties: {
    /**
     * Proposer's balance is too low.
     **/
    InsufficientProposersBalance: GenericModuleError;

    /**
     * No proposal or bounty at that index.
     **/
    InvalidIndex: GenericModuleError;

    /**
     * The reason given is just too big.
     **/
    ReasonTooBig: GenericModuleError;

    /**
     * The bounty status is unexpected.
     **/
    UnexpectedStatus: GenericModuleError;

    /**
     * Require bounty curator.
     **/
    RequireCurator: GenericModuleError;

    /**
     * Invalid bounty value.
     **/
    InvalidValue: GenericModuleError;

    /**
     * Invalid bounty fee.
     **/
    InvalidFee: GenericModuleError;

    /**
     * A bounty payout is pending.
     * To cancel the bounty, you must unassign and slash the curator.
     **/
    PendingPayout: GenericModuleError;

    /**
     * The bounties cannot be claimed/closed because it's still in the countdown period.
     **/
    Premature: GenericModuleError;

    /**
     * The bounty cannot be closed because it has active child bounties.
     **/
    HasActiveChildBounty: GenericModuleError;

    /**
     * Too many approvals are already queued.
     **/
    TooManyQueued: GenericModuleError;
  };
  tips: {
    /**
     * The reason given is just too big.
     **/
    ReasonTooBig: GenericModuleError;

    /**
     * The tip was already found/started.
     **/
    AlreadyKnown: GenericModuleError;

    /**
     * The tip hash is unknown.
     **/
    UnknownTip: GenericModuleError;

    /**
     * The account attempting to retract the tip is not the finder of the tip.
     **/
    NotFinder: GenericModuleError;

    /**
     * The tip cannot be claimed/closed because there are not enough tippers yet.
     **/
    StillOpen: GenericModuleError;

    /**
     * The tip cannot be claimed/closed because it's still in the countdown period.
     **/
    Premature: GenericModuleError;
  };
  assets: {
    /**
     * Account balance must be greater than or equal to the transfer amount.
     **/
    BalanceLow: GenericModuleError;

    /**
     * The account to alter does not exist.
     **/
    NoAccount: GenericModuleError;

    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * The given asset ID is unknown.
     **/
    Unknown: GenericModuleError;

    /**
     * The origin account is frozen.
     **/
    Frozen: GenericModuleError;

    /**
     * The asset ID is already taken.
     **/
    InUse: GenericModuleError;

    /**
     * Invalid witness data given.
     **/
    BadWitness: GenericModuleError;

    /**
     * Minimum balance should be non-zero.
     **/
    MinBalanceZero: GenericModuleError;

    /**
     * Unable to increment the consumer reference counters on the account. Either no provider
     * reference exists to allow a non-zero balance of a non-self-sufficient asset, or one
     * fewer then the maximum number of consumers has been reached.
     **/
    UnavailableConsumer: GenericModuleError;

    /**
     * Invalid metadata given.
     **/
    BadMetadata: GenericModuleError;

    /**
     * No approval exists that would allow the transfer.
     **/
    Unapproved: GenericModuleError;

    /**
     * The source account would not survive the transfer and it needs to stay alive.
     **/
    WouldDie: GenericModuleError;

    /**
     * The asset-account already exists.
     **/
    AlreadyExists: GenericModuleError;

    /**
     * The asset-account doesn't have an associated deposit.
     **/
    NoDeposit: GenericModuleError;

    /**
     * The operation would result in funds being burned.
     **/
    WouldBurn: GenericModuleError;

    /**
     * The asset is a live asset and is actively being used. Usually emit for operations such
     * as `start_destroy` which require the asset to be in a destroying state.
     **/
    LiveAsset: GenericModuleError;

    /**
     * The asset is not live, and likely being destroyed.
     **/
    AssetNotLive: GenericModuleError;

    /**
     * The asset status is not the expected status.
     **/
    IncorrectStatus: GenericModuleError;

    /**
     * The asset should be frozen before the given operation.
     **/
    NotFrozen: GenericModuleError;

    /**
     * Callback action resulted in error
     **/
    CallbackFailed: GenericModuleError;
  };
  poolAssets: {
    /**
     * Account balance must be greater than or equal to the transfer amount.
     **/
    BalanceLow: GenericModuleError;

    /**
     * The account to alter does not exist.
     **/
    NoAccount: GenericModuleError;

    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * The given asset ID is unknown.
     **/
    Unknown: GenericModuleError;

    /**
     * The origin account is frozen.
     **/
    Frozen: GenericModuleError;

    /**
     * The asset ID is already taken.
     **/
    InUse: GenericModuleError;

    /**
     * Invalid witness data given.
     **/
    BadWitness: GenericModuleError;

    /**
     * Minimum balance should be non-zero.
     **/
    MinBalanceZero: GenericModuleError;

    /**
     * Unable to increment the consumer reference counters on the account. Either no provider
     * reference exists to allow a non-zero balance of a non-self-sufficient asset, or one
     * fewer then the maximum number of consumers has been reached.
     **/
    UnavailableConsumer: GenericModuleError;

    /**
     * Invalid metadata given.
     **/
    BadMetadata: GenericModuleError;

    /**
     * No approval exists that would allow the transfer.
     **/
    Unapproved: GenericModuleError;

    /**
     * The source account would not survive the transfer and it needs to stay alive.
     **/
    WouldDie: GenericModuleError;

    /**
     * The asset-account already exists.
     **/
    AlreadyExists: GenericModuleError;

    /**
     * The asset-account doesn't have an associated deposit.
     **/
    NoDeposit: GenericModuleError;

    /**
     * The operation would result in funds being burned.
     **/
    WouldBurn: GenericModuleError;

    /**
     * The asset is a live asset and is actively being used. Usually emit for operations such
     * as `start_destroy` which require the asset to be in a destroying state.
     **/
    LiveAsset: GenericModuleError;

    /**
     * The asset is not live, and likely being destroyed.
     **/
    AssetNotLive: GenericModuleError;

    /**
     * The asset status is not the expected status.
     **/
    IncorrectStatus: GenericModuleError;

    /**
     * The asset should be frozen before the given operation.
     **/
    NotFrozen: GenericModuleError;

    /**
     * Callback action resulted in error
     **/
    CallbackFailed: GenericModuleError;
  };
  lottery: {
    /**
     * A lottery has not been configured.
     **/
    NotConfigured: GenericModuleError;

    /**
     * A lottery is already in progress.
     **/
    InProgress: GenericModuleError;

    /**
     * A lottery has already ended.
     **/
    AlreadyEnded: GenericModuleError;

    /**
     * The call is not valid for an open lottery.
     **/
    InvalidCall: GenericModuleError;

    /**
     * You are already participating in the lottery with this call.
     **/
    AlreadyParticipating: GenericModuleError;

    /**
     * Too many calls for a single lottery.
     **/
    TooManyCalls: GenericModuleError;

    /**
     * Failed to encode calls
     **/
    EncodingFailed: GenericModuleError;
  };
  nis: {
    /**
     * The duration of the bid is less than one.
     **/
    DurationTooSmall: GenericModuleError;

    /**
     * The duration is the bid is greater than the number of queues.
     **/
    DurationTooBig: GenericModuleError;

    /**
     * The amount of the bid is less than the minimum allowed.
     **/
    AmountTooSmall: GenericModuleError;

    /**
     * The queue for the bid's duration is full and the amount bid is too low to get in
     * through replacing an existing bid.
     **/
    BidTooLow: GenericModuleError;

    /**
     * Receipt index is unknown.
     **/
    UnknownReceipt: GenericModuleError;

    /**
     * Not the owner of the receipt.
     **/
    NotOwner: GenericModuleError;

    /**
     * Bond not yet at expiry date.
     **/
    NotExpired: GenericModuleError;

    /**
     * The given bid for retraction is not found.
     **/
    UnknownBid: GenericModuleError;

    /**
     * The portion supplied is beyond the value of the receipt.
     **/
    PortionTooBig: GenericModuleError;

    /**
     * Not enough funds are held to pay out.
     **/
    Unfunded: GenericModuleError;

    /**
     * There are enough funds for what is required.
     **/
    AlreadyFunded: GenericModuleError;

    /**
     * The thaw throttle has been reached for this period.
     **/
    Throttled: GenericModuleError;

    /**
     * The operation would result in a receipt worth an insignficant value.
     **/
    MakesDust: GenericModuleError;

    /**
     * The receipt is already communal.
     **/
    AlreadyCommunal: GenericModuleError;

    /**
     * The receipt is already private.
     **/
    AlreadyPrivate: GenericModuleError;
  };
  uniques: {
    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * The given item ID is unknown.
     **/
    UnknownCollection: GenericModuleError;

    /**
     * The item ID has already been used for an item.
     **/
    AlreadyExists: GenericModuleError;

    /**
     * The owner turned out to be different to what was expected.
     **/
    WrongOwner: GenericModuleError;

    /**
     * Invalid witness data given.
     **/
    BadWitness: GenericModuleError;

    /**
     * The item ID is already taken.
     **/
    InUse: GenericModuleError;

    /**
     * The item or collection is frozen.
     **/
    Frozen: GenericModuleError;

    /**
     * The delegate turned out to be different to what was expected.
     **/
    WrongDelegate: GenericModuleError;

    /**
     * There is no delegate approved.
     **/
    NoDelegate: GenericModuleError;

    /**
     * No approval exists that would allow the transfer.
     **/
    Unapproved: GenericModuleError;

    /**
     * The named owner has not signed ownership of the collection is acceptable.
     **/
    Unaccepted: GenericModuleError;

    /**
     * The item is locked.
     **/
    Locked: GenericModuleError;

    /**
     * All items have been minted.
     **/
    MaxSupplyReached: GenericModuleError;

    /**
     * The max supply has already been set.
     **/
    MaxSupplyAlreadySet: GenericModuleError;

    /**
     * The provided max supply is less to the amount of items a collection already has.
     **/
    MaxSupplyTooSmall: GenericModuleError;

    /**
     * The given item ID is unknown.
     **/
    UnknownItem: GenericModuleError;

    /**
     * Item is not for sale.
     **/
    NotForSale: GenericModuleError;

    /**
     * The provided bid is too low.
     **/
    BidTooLow: GenericModuleError;
  };
  nfts: {
    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * The given item ID is unknown.
     **/
    UnknownCollection: GenericModuleError;

    /**
     * The item ID has already been used for an item.
     **/
    AlreadyExists: GenericModuleError;

    /**
     * The approval had a deadline that expired, so the approval isn't valid anymore.
     **/
    ApprovalExpired: GenericModuleError;

    /**
     * The owner turned out to be different to what was expected.
     **/
    WrongOwner: GenericModuleError;

    /**
     * The witness data given does not match the current state of the chain.
     **/
    BadWitness: GenericModuleError;

    /**
     * Collection ID is already taken.
     **/
    CollectionIdInUse: GenericModuleError;

    /**
     * Items within that collection are non-transferable.
     **/
    ItemsNonTransferable: GenericModuleError;

    /**
     * The provided account is not a delegate.
     **/
    NotDelegate: GenericModuleError;

    /**
     * The delegate turned out to be different to what was expected.
     **/
    WrongDelegate: GenericModuleError;

    /**
     * No approval exists that would allow the transfer.
     **/
    Unapproved: GenericModuleError;

    /**
     * The named owner has not signed ownership acceptance of the collection.
     **/
    Unaccepted: GenericModuleError;

    /**
     * The item is locked (non-transferable).
     **/
    ItemLocked: GenericModuleError;

    /**
     * Item's attributes are locked.
     **/
    LockedItemAttributes: GenericModuleError;

    /**
     * Collection's attributes are locked.
     **/
    LockedCollectionAttributes: GenericModuleError;

    /**
     * Item's metadata is locked.
     **/
    LockedItemMetadata: GenericModuleError;

    /**
     * Collection's metadata is locked.
     **/
    LockedCollectionMetadata: GenericModuleError;

    /**
     * All items have been minted.
     **/
    MaxSupplyReached: GenericModuleError;

    /**
     * The max supply is locked and can't be changed.
     **/
    MaxSupplyLocked: GenericModuleError;

    /**
     * The provided max supply is less than the number of items a collection already has.
     **/
    MaxSupplyTooSmall: GenericModuleError;

    /**
     * The given item ID is unknown.
     **/
    UnknownItem: GenericModuleError;

    /**
     * Swap doesn't exist.
     **/
    UnknownSwap: GenericModuleError;

    /**
     * The given item has no metadata set.
     **/
    MetadataNotFound: GenericModuleError;

    /**
     * The provided attribute can't be found.
     **/
    AttributeNotFound: GenericModuleError;

    /**
     * Item is not for sale.
     **/
    NotForSale: GenericModuleError;

    /**
     * The provided bid is too low.
     **/
    BidTooLow: GenericModuleError;

    /**
     * The item has reached its approval limit.
     **/
    ReachedApprovalLimit: GenericModuleError;

    /**
     * The deadline has already expired.
     **/
    DeadlineExpired: GenericModuleError;

    /**
     * The duration provided should be less than or equal to `MaxDeadlineDuration`.
     **/
    WrongDuration: GenericModuleError;

    /**
     * The method is disabled by system settings.
     **/
    MethodDisabled: GenericModuleError;

    /**
     * The provided setting can't be set.
     **/
    WrongSetting: GenericModuleError;

    /**
     * Item's config already exists and should be equal to the provided one.
     **/
    InconsistentItemConfig: GenericModuleError;

    /**
     * Config for a collection or an item can't be found.
     **/
    NoConfig: GenericModuleError;

    /**
     * Some roles were not cleared.
     **/
    RolesNotCleared: GenericModuleError;

    /**
     * Mint has not started yet.
     **/
    MintNotStarted: GenericModuleError;

    /**
     * Mint has already ended.
     **/
    MintEnded: GenericModuleError;

    /**
     * The provided Item was already used for claiming.
     **/
    AlreadyClaimed: GenericModuleError;

    /**
     * The provided data is incorrect.
     **/
    IncorrectData: GenericModuleError;

    /**
     * The extrinsic was sent by the wrong origin.
     **/
    WrongOrigin: GenericModuleError;

    /**
     * The provided signature is incorrect.
     **/
    WrongSignature: GenericModuleError;

    /**
     * The provided metadata might be too long.
     **/
    IncorrectMetadata: GenericModuleError;

    /**
     * Can't set more attributes per one call.
     **/
    MaxAttributesLimitReached: GenericModuleError;

    /**
     * The provided namespace isn't supported in this call.
     **/
    WrongNamespace: GenericModuleError;

    /**
     * Can't delete non-empty collections.
     **/
    CollectionNotEmpty: GenericModuleError;

    /**
     * The witness data should be provided.
     **/
    WitnessRequired: GenericModuleError;
  };
  nftFractionalization: {
    /**
     * Asset ID does not correspond to locked NFT.
     **/
    IncorrectAssetId: GenericModuleError;

    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * NFT doesn't exist.
     **/
    NftNotFound: GenericModuleError;

    /**
     * NFT has not yet been fractionalised.
     **/
    NftNotFractionalized: GenericModuleError;
  };
  salary: {
    /**
     * The salary system has already been started.
     **/
    AlreadyStarted: GenericModuleError;

    /**
     * The account is not a ranked member.
     **/
    NotMember: GenericModuleError;

    /**
     * The account is already inducted.
     **/
    AlreadyInducted: GenericModuleError;
    NotInducted: GenericModuleError;

    /**
     * The member does not have a current valid claim.
     **/
    NoClaim: GenericModuleError;

    /**
     * The member's claim is zero.
     **/
    ClaimZero: GenericModuleError;

    /**
     * Current cycle's registration period is over.
     **/
    TooLate: GenericModuleError;

    /**
     * Current cycle's payment period is not yet begun.
     **/
    TooEarly: GenericModuleError;

    /**
     * Cycle is not yet over.
     **/
    NotYet: GenericModuleError;

    /**
     * The payout cycles have not yet started.
     **/
    NotStarted: GenericModuleError;

    /**
     * There is no budget left for the payout.
     **/
    Bankrupt: GenericModuleError;

    /**
     * There was some issue with the mechanism of payment.
     **/
    PayError: GenericModuleError;

    /**
     * The payment has neither failed nor succeeded yet.
     **/
    Inconclusive: GenericModuleError;

    /**
     * The cycle is after that in which the payment was made.
     **/
    NotCurrent: GenericModuleError;
  };
  coreFellowship: {
    /**
     * Member's rank is too low.
     **/
    Unranked: GenericModuleError;

    /**
     * Member's rank is not zero.
     **/
    Ranked: GenericModuleError;

    /**
     * Member's rank is not as expected - generally means that the rank provided to the call
     * does not agree with the state of the system.
     **/
    UnexpectedRank: GenericModuleError;

    /**
     * The given rank is invalid - this generally means it's not between 1 and `RANK_COUNT`.
     **/
    InvalidRank: GenericModuleError;

    /**
     * The origin does not have enough permission to do this operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * No work needs to be done at present for this member.
     **/
    NothingDoing: GenericModuleError;

    /**
     * The candidate has already been inducted. This should never happen since it would
     * require a candidate (rank 0) to already be tracked in the pallet.
     **/
    AlreadyInducted: GenericModuleError;

    /**
     * The candidate has not been inducted, so cannot be offboarded from this pallet.
     **/
    NotTracked: GenericModuleError;

    /**
     * Operation cannot be done yet since not enough time has passed.
     **/
    TooSoon: GenericModuleError;
  };
  transactionStorage: {
    /**
     * Insufficient account balance.
     **/
    InsufficientFunds: GenericModuleError;

    /**
     * Invalid configuration.
     **/
    NotConfigured: GenericModuleError;

    /**
     * Renewed extrinsic is not found.
     **/
    RenewedNotFound: GenericModuleError;

    /**
     * Attempting to store empty transaction
     **/
    EmptyTransaction: GenericModuleError;

    /**
     * Proof was not expected in this block.
     **/
    UnexpectedProof: GenericModuleError;

    /**
     * Proof failed verification.
     **/
    InvalidProof: GenericModuleError;

    /**
     * Missing storage proof.
     **/
    MissingProof: GenericModuleError;

    /**
     * Unable to verify proof becasue state data is missing.
     **/
    MissingStateData: GenericModuleError;

    /**
     * Double proof check in the block.
     **/
    DoubleCheck: GenericModuleError;

    /**
     * Storage proof was not checked in the block.
     **/
    ProofNotChecked: GenericModuleError;

    /**
     * Transaction is too large.
     **/
    TransactionTooLarge: GenericModuleError;

    /**
     * Too many transactions in the block.
     **/
    TooManyTransactions: GenericModuleError;

    /**
     * Attempted to call `store` outside of block execution.
     **/
    BadContext: GenericModuleError;
  };
  voterList: {
    /**
     * A error in the list interface implementation.
     **/
    List: GenericModuleError;
  };
  stateTrieMigration: {
    /**
     * Max signed limits not respected.
     **/
    MaxSignedLimits: GenericModuleError;

    /**
     * A key was longer than the configured maximum.
     *
     * This means that the migration halted at the current [`Progress`] and
     * can be resumed with a larger [`crate::Config::MaxKeyLen`] value.
     * Retrying with the same [`crate::Config::MaxKeyLen`] value will not work.
     * The value should only be increased to avoid a storage migration for the currently
     * stored [`crate::Progress::LastKey`].
     **/
    KeyTooLong: GenericModuleError;

    /**
     * submitter does not have enough funds.
     **/
    NotEnoughFunds: GenericModuleError;

    /**
     * Bad witness data provided.
     **/
    BadWitness: GenericModuleError;

    /**
     * Signed migration is not allowed because the maximum limit is not set yet.
     **/
    SignedMigrationNotAllowed: GenericModuleError;

    /**
     * Bad child root provided.
     **/
    BadChildRoot: GenericModuleError;
  };
  childBounties: {
    /**
     * The parent bounty is not in active state.
     **/
    ParentBountyNotActive: GenericModuleError;

    /**
     * The bounty balance is not enough to add new child-bounty.
     **/
    InsufficientBountyBalance: GenericModuleError;

    /**
     * Number of child bounties exceeds limit `MaxActiveChildBountyCount`.
     **/
    TooManyChildBounties: GenericModuleError;
  };
  referenda: {
    /**
     * Referendum is not ongoing.
     **/
    NotOngoing: GenericModuleError;

    /**
     * Referendum's decision deposit is already paid.
     **/
    HasDeposit: GenericModuleError;

    /**
     * The track identifier given was invalid.
     **/
    BadTrack: GenericModuleError;

    /**
     * There are already a full complement of referenda in progress for this track.
     **/
    Full: GenericModuleError;

    /**
     * The queue of the track is empty.
     **/
    QueueEmpty: GenericModuleError;

    /**
     * The referendum index provided is invalid in this context.
     **/
    BadReferendum: GenericModuleError;

    /**
     * There was nothing to do in the advancement.
     **/
    NothingToDo: GenericModuleError;

    /**
     * No track exists for the proposal origin.
     **/
    NoTrack: GenericModuleError;

    /**
     * Any deposit cannot be refunded until after the decision is over.
     **/
    Unfinished: GenericModuleError;

    /**
     * The deposit refunder is not the depositor.
     **/
    NoPermission: GenericModuleError;

    /**
     * The deposit cannot be refunded since none was made.
     **/
    NoDeposit: GenericModuleError;

    /**
     * The referendum status is invalid for this operation.
     **/
    BadStatus: GenericModuleError;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericModuleError;
  };
  remark: {
    /**
     * Attempting to store empty data.
     **/
    Empty: GenericModuleError;

    /**
     * Attempted to call `store` outside of block execution.
     **/
    BadContext: GenericModuleError;
  };
  convictionVoting: {
    /**
     * Poll is not ongoing.
     **/
    NotOngoing: GenericModuleError;

    /**
     * The given account did not vote on the poll.
     **/
    NotVoter: GenericModuleError;

    /**
     * The actor has no permission to conduct the action.
     **/
    NoPermission: GenericModuleError;

    /**
     * The actor has no permission to conduct the action right now but will do in the future.
     **/
    NoPermissionYet: GenericModuleError;

    /**
     * The account is already delegating.
     **/
    AlreadyDelegating: GenericModuleError;

    /**
     * The account currently has votes attached to it and the operation cannot succeed until
     * these are removed, either through `unvote` or `reap_vote`.
     **/
    AlreadyVoting: GenericModuleError;

    /**
     * Too high a balance was provided that the account cannot afford.
     **/
    InsufficientFunds: GenericModuleError;

    /**
     * The account is not currently delegating.
     **/
    NotDelegating: GenericModuleError;

    /**
     * Delegation to oneself makes no sense.
     **/
    Nonsense: GenericModuleError;

    /**
     * Maximum number of votes reached.
     **/
    MaxVotesReached: GenericModuleError;

    /**
     * The class must be supplied since it is not easily determinable from the state.
     **/
    ClassNeeded: GenericModuleError;

    /**
     * The class ID supplied is invalid.
     **/
    BadClass: GenericModuleError;
  };
  whitelist: {
    /**
     * The preimage of the call hash could not be loaded.
     **/
    UnavailablePreImage: GenericModuleError;

    /**
     * The call could not be decoded.
     **/
    UndecodableCall: GenericModuleError;

    /**
     * The weight of the decoded call was higher than the witness.
     **/
    InvalidCallWeightWitness: GenericModuleError;

    /**
     * The call was not whitelisted.
     **/
    CallIsNotWhitelisted: GenericModuleError;

    /**
     * The call was already whitelisted; No-Op.
     **/
    CallAlreadyWhitelisted: GenericModuleError;
  };
  allianceMotion: {
    /**
     * Account is not a member
     **/
    NotMember: GenericModuleError;

    /**
     * Duplicate proposals not allowed
     **/
    DuplicateProposal: GenericModuleError;

    /**
     * Proposal must exist
     **/
    ProposalMissing: GenericModuleError;

    /**
     * Mismatched index
     **/
    WrongIndex: GenericModuleError;

    /**
     * Duplicate vote ignored
     **/
    DuplicateVote: GenericModuleError;

    /**
     * Members are already initialized!
     **/
    AlreadyInitialized: GenericModuleError;

    /**
     * The close call was made too early, before the end of the voting.
     **/
    TooEarly: GenericModuleError;

    /**
     * There can only be a maximum of `MaxProposals` active proposals.
     **/
    TooManyProposals: GenericModuleError;

    /**
     * The given weight bound for the proposal was too low.
     **/
    WrongProposalWeight: GenericModuleError;

    /**
     * The given length bound for the proposal was too low.
     **/
    WrongProposalLength: GenericModuleError;

    /**
     * Prime account is not a member
     **/
    PrimeAccountNotMember: GenericModuleError;
  };
  alliance: {
    /**
     * The Alliance has not been initialized yet, therefore accounts cannot join it.
     **/
    AllianceNotYetInitialized: GenericModuleError;

    /**
     * The Alliance has been initialized, therefore cannot be initialized again.
     **/
    AllianceAlreadyInitialized: GenericModuleError;

    /**
     * Account is already a member.
     **/
    AlreadyMember: GenericModuleError;

    /**
     * Account is not a member.
     **/
    NotMember: GenericModuleError;

    /**
     * Account is not an ally.
     **/
    NotAlly: GenericModuleError;

    /**
     * Account does not have voting rights.
     **/
    NoVotingRights: GenericModuleError;

    /**
     * Account is already an elevated (fellow) member.
     **/
    AlreadyElevated: GenericModuleError;

    /**
     * Item is already listed as unscrupulous.
     **/
    AlreadyUnscrupulous: GenericModuleError;

    /**
     * Account has been deemed unscrupulous by the Alliance and is not welcome to join or be
     * nominated.
     **/
    AccountNonGrata: GenericModuleError;

    /**
     * Item has not been deemed unscrupulous.
     **/
    NotListedAsUnscrupulous: GenericModuleError;

    /**
     * The number of unscrupulous items exceeds `MaxUnscrupulousItems`.
     **/
    TooManyUnscrupulousItems: GenericModuleError;

    /**
     * Length of website URL exceeds `MaxWebsiteUrlLength`.
     **/
    TooLongWebsiteUrl: GenericModuleError;

    /**
     * Balance is insufficient for the required deposit.
     **/
    InsufficientFunds: GenericModuleError;

    /**
     * The account's identity does not have display field and website field.
     **/
    WithoutIdentityDisplayAndWebsite: GenericModuleError;

    /**
     * The account's identity has no good judgement.
     **/
    WithoutGoodIdentityJudgement: GenericModuleError;

    /**
     * The proposal hash is not found.
     **/
    MissingProposalHash: GenericModuleError;

    /**
     * The announcement is not found.
     **/
    MissingAnnouncement: GenericModuleError;

    /**
     * Number of members exceeds `MaxMembersCount`.
     **/
    TooManyMembers: GenericModuleError;

    /**
     * Number of announcements exceeds `MaxAnnouncementsCount`.
     **/
    TooManyAnnouncements: GenericModuleError;

    /**
     * Invalid witness data given.
     **/
    BadWitness: GenericModuleError;

    /**
     * Account already gave retirement notice
     **/
    AlreadyRetiring: GenericModuleError;

    /**
     * Account did not give a retirement notice required to retire.
     **/
    RetirementNoticeNotGiven: GenericModuleError;

    /**
     * Retirement period has not passed.
     **/
    RetirementPeriodNotPassed: GenericModuleError;

    /**
     * Fellows must be provided to initialize the Alliance.
     **/
    FellowsMissing: GenericModuleError;
  };
  nominationPools: {
    /**
     * A (bonded) pool id does not exist.
     **/
    PoolNotFound: GenericModuleError;

    /**
     * An account is not a member.
     **/
    PoolMemberNotFound: GenericModuleError;

    /**
     * A reward pool does not exist. In all cases this is a system logic error.
     **/
    RewardPoolNotFound: GenericModuleError;

    /**
     * A sub pool does not exist.
     **/
    SubPoolsNotFound: GenericModuleError;

    /**
     * An account is already delegating in another pool. An account may only belong to one
     * pool at a time.
     **/
    AccountBelongsToOtherPool: GenericModuleError;

    /**
     * The member is fully unbonded (and thus cannot access the bonded and reward pool
     * anymore to, for example, collect rewards).
     **/
    FullyUnbonding: GenericModuleError;

    /**
     * The member cannot unbond further chunks due to reaching the limit.
     **/
    MaxUnbondingLimit: GenericModuleError;

    /**
     * None of the funds can be withdrawn yet because the bonding duration has not passed.
     **/
    CannotWithdrawAny: GenericModuleError;

    /**
     * The amount does not meet the minimum bond to either join or create a pool.
     *
     * The depositor can never unbond to a value less than
     * `Pallet::depositor_min_bond`. The caller does not have nominating
     * permissions for the pool. Members can never unbond to a value below `MinJoinBond`.
     **/
    MinimumBondNotMet: GenericModuleError;

    /**
     * The transaction could not be executed due to overflow risk for the pool.
     **/
    OverflowRisk: GenericModuleError;

    /**
     * A pool must be in [`PoolState::Destroying`] in order for the depositor to unbond or for
     * other members to be permissionlessly unbonded.
     **/
    NotDestroying: GenericModuleError;

    /**
     * The caller does not have nominating permissions for the pool.
     **/
    NotNominator: GenericModuleError;

    /**
     * Either a) the caller cannot make a valid kick or b) the pool is not destroying.
     **/
    NotKickerOrDestroying: GenericModuleError;

    /**
     * The pool is not open to join
     **/
    NotOpen: GenericModuleError;

    /**
     * The system is maxed out on pools.
     **/
    MaxPools: GenericModuleError;

    /**
     * Too many members in the pool or system.
     **/
    MaxPoolMembers: GenericModuleError;

    /**
     * The pools state cannot be changed.
     **/
    CanNotChangeState: GenericModuleError;

    /**
     * The caller does not have adequate permissions.
     **/
    DoesNotHavePermission: GenericModuleError;

    /**
     * Metadata exceeds [`Config::MaxMetadataLen`]
     **/
    MetadataExceedsMaxLen: GenericModuleError;

    /**
     * Some error occurred that should never happen. This should be reported to the
     * maintainers.
     **/
    Defensive: GenericModuleError;

    /**
     * Partial unbonding now allowed permissionlessly.
     **/
    PartialUnbondNotAllowedPermissionlessly: GenericModuleError;

    /**
     * The pool's max commission cannot be set higher than the existing value.
     **/
    MaxCommissionRestricted: GenericModuleError;

    /**
     * The supplied commission exceeds the max allowed commission.
     **/
    CommissionExceedsMaximum: GenericModuleError;

    /**
     * The supplied commission exceeds global maximum commission.
     **/
    CommissionExceedsGlobalMaximum: GenericModuleError;

    /**
     * Not enough blocks have surpassed since the last commission update.
     **/
    CommissionChangeThrottled: GenericModuleError;

    /**
     * The submitted changes to commission change rate are not allowed.
     **/
    CommissionChangeRateNotAllowed: GenericModuleError;

    /**
     * There is no pending commission to claim.
     **/
    NoPendingCommission: GenericModuleError;

    /**
     * No commission current has been set.
     **/
    NoCommissionCurrentSet: GenericModuleError;

    /**
     * Pool id currently in use.
     **/
    PoolIdInUse: GenericModuleError;

    /**
     * Pool id provided is not correct/usable.
     **/
    InvalidPoolId: GenericModuleError;

    /**
     * Bonding extra is restricted to the exact pending reward amount.
     **/
    BondExtraRestricted: GenericModuleError;
  };
  rankedPolls: {
    /**
     * Referendum is not ongoing.
     **/
    NotOngoing: GenericModuleError;

    /**
     * Referendum's decision deposit is already paid.
     **/
    HasDeposit: GenericModuleError;

    /**
     * The track identifier given was invalid.
     **/
    BadTrack: GenericModuleError;

    /**
     * There are already a full complement of referenda in progress for this track.
     **/
    Full: GenericModuleError;

    /**
     * The queue of the track is empty.
     **/
    QueueEmpty: GenericModuleError;

    /**
     * The referendum index provided is invalid in this context.
     **/
    BadReferendum: GenericModuleError;

    /**
     * There was nothing to do in the advancement.
     **/
    NothingToDo: GenericModuleError;

    /**
     * No track exists for the proposal origin.
     **/
    NoTrack: GenericModuleError;

    /**
     * Any deposit cannot be refunded until after the decision is over.
     **/
    Unfinished: GenericModuleError;

    /**
     * The deposit refunder is not the depositor.
     **/
    NoPermission: GenericModuleError;

    /**
     * The deposit cannot be refunded since none was made.
     **/
    NoDeposit: GenericModuleError;

    /**
     * The referendum status is invalid for this operation.
     **/
    BadStatus: GenericModuleError;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericModuleError;
  };
  rankedCollective: {
    /**
     * Account is already a member.
     **/
    AlreadyMember: GenericModuleError;

    /**
     * Account is not a member.
     **/
    NotMember: GenericModuleError;

    /**
     * The given poll index is unknown or has closed.
     **/
    NotPolling: GenericModuleError;

    /**
     * The given poll is still ongoing.
     **/
    Ongoing: GenericModuleError;

    /**
     * There are no further records to be removed.
     **/
    NoneRemaining: GenericModuleError;

    /**
     * Unexpected error in state.
     **/
    Corruption: GenericModuleError;

    /**
     * The member's rank is too low to vote.
     **/
    RankTooLow: GenericModuleError;

    /**
     * The information provided is incorrect.
     **/
    InvalidWitness: GenericModuleError;

    /**
     * The origin is not sufficiently privileged to do the operation.
     **/
    NoPermission: GenericModuleError;
  };
  assetConversion: {
    /**
     * Provided assets are equal.
     **/
    EqualAssets: GenericModuleError;

    /**
     * Provided asset is not supported for pool.
     **/
    UnsupportedAsset: GenericModuleError;

    /**
     * Pool already exists.
     **/
    PoolExists: GenericModuleError;

    /**
     * Desired amount can't be zero.
     **/
    WrongDesiredAmount: GenericModuleError;

    /**
     * Provided amount should be greater than or equal to the existential deposit/asset's
     * minimal amount.
     **/
    AmountOneLessThanMinimal: GenericModuleError;

    /**
     * Provided amount should be greater than or equal to the existential deposit/asset's
     * minimal amount.
     **/
    AmountTwoLessThanMinimal: GenericModuleError;

    /**
     * Reserve needs to always be greater than or equal to the existential deposit/asset's
     * minimal amount.
     **/
    ReserveLeftLessThanMinimal: GenericModuleError;

    /**
     * Desired amount can't be equal to the pool reserve.
     **/
    AmountOutTooHigh: GenericModuleError;

    /**
     * The pool doesn't exist.
     **/
    PoolNotFound: GenericModuleError;

    /**
     * An overflow happened.
     **/
    Overflow: GenericModuleError;

    /**
     * The minimal amount requirement for the first token in the pair wasn't met.
     **/
    AssetOneDepositDidNotMeetMinimum: GenericModuleError;

    /**
     * The minimal amount requirement for the second token in the pair wasn't met.
     **/
    AssetTwoDepositDidNotMeetMinimum: GenericModuleError;

    /**
     * The minimal amount requirement for the first token in the pair wasn't met.
     **/
    AssetOneWithdrawalDidNotMeetMinimum: GenericModuleError;

    /**
     * The minimal amount requirement for the second token in the pair wasn't met.
     **/
    AssetTwoWithdrawalDidNotMeetMinimum: GenericModuleError;

    /**
     * Optimal calculated amount is less than desired.
     **/
    OptimalAmountLessThanDesired: GenericModuleError;

    /**
     * Insufficient liquidity minted.
     **/
    InsufficientLiquidityMinted: GenericModuleError;

    /**
     * Requested liquidity can't be zero.
     **/
    ZeroLiquidity: GenericModuleError;

    /**
     * Amount can't be zero.
     **/
    ZeroAmount: GenericModuleError;

    /**
     * Insufficient liquidity in the pool.
     **/
    InsufficientLiquidity: GenericModuleError;

    /**
     * Calculated amount out is less than provided minimum amount.
     **/
    ProvidedMinimumNotSufficientForSwap: GenericModuleError;

    /**
     * Provided maximum amount is not sufficient for swap.
     **/
    ProvidedMaximumNotSufficientForSwap: GenericModuleError;

    /**
     * Only pools with native on one side are valid.
     **/
    PoolMustContainNativeCurrency: GenericModuleError;

    /**
     * The provided path must consists of 2 assets at least.
     **/
    InvalidPath: GenericModuleError;

    /**
     * It was not possible to calculate path data.
     **/
    PathError: GenericModuleError;

    /**
     * The provided path must consists of unique assets.
     **/
    NonUniquePath: GenericModuleError;

    /**
     * It was not possible to get or increment the Id of the pool.
     **/
    IncorrectPoolAssetId: GenericModuleError;

    /**
     * Unable to find an element in an array/vec that should have one-to-one correspondence
     * with another. For example, an array of assets constituting a `path` should have a
     * corresponding array of `amounts` along the path.
     **/
    CorrespondenceError: GenericModuleError;
  };
  fastUnstake: {
    /**
     * The provided Controller account was not found.
     *
     * This means that the given account is not bonded.
     **/
    NotController: GenericModuleError;

    /**
     * The bonded account has already been queued.
     **/
    AlreadyQueued: GenericModuleError;

    /**
     * The bonded account has active unlocking chunks.
     **/
    NotFullyBonded: GenericModuleError;

    /**
     * The provided un-staker is not in the `Queue`.
     **/
    NotQueued: GenericModuleError;

    /**
     * The provided un-staker is already in Head, and cannot deregister.
     **/
    AlreadyHead: GenericModuleError;

    /**
     * The call is not allowed at this point because the pallet is not active.
     **/
    CallNotAllowed: GenericModuleError;
  };
  messageQueue: {
    /**
     * Page is not reapable because it has items remaining to be processed and is not old
     * enough.
     **/
    NotReapable: GenericModuleError;

    /**
     * Page to be reaped does not exist.
     **/
    NoPage: GenericModuleError;

    /**
     * The referenced message could not be found.
     **/
    NoMessage: GenericModuleError;

    /**
     * The message was already processed and cannot be processed again.
     **/
    AlreadyProcessed: GenericModuleError;

    /**
     * The message is queued for future execution.
     **/
    Queued: GenericModuleError;

    /**
     * There is temporarily not enough weight to continue servicing messages.
     **/
    InsufficientWeight: GenericModuleError;

    /**
     * This message is temporarily unprocessable.
     *
     * Such errors are expected, but not guaranteed, to resolve themselves eventually through
     * retrying.
     **/
    TemporarilyUnprocessable: GenericModuleError;

    /**
     * The queue is paused and no message can be executed from it.
     *
     * This can change at any time and may resolve in the future by re-trying.
     **/
    QueuePaused: GenericModuleError;
  };
  txPause: {
    /**
     * The call is paused.
     **/
    IsPaused: GenericModuleError;

    /**
     * The call is unpaused.
     **/
    IsUnpaused: GenericModuleError;

    /**
     * The call is whitelisted and cannot be paused.
     **/
    Unpausable: GenericModuleError;
    NotFound: GenericModuleError;
  };
  safeMode: {
    /**
     * The safe-mode is (already or still) entered.
     **/
    Entered: GenericModuleError;

    /**
     * The safe-mode is (already or still) exited.
     **/
    Exited: GenericModuleError;

    /**
     * This functionality of the pallet is disabled by the configuration.
     **/
    NotConfigured: GenericModuleError;

    /**
     * There is no balance reserved.
     **/
    NoDeposit: GenericModuleError;

    /**
     * The account already has a deposit reserved and can therefore not enter or extend again.
     **/
    AlreadyDeposited: GenericModuleError;

    /**
     * This deposit cannot be released yet.
     **/
    CannotReleaseYet: GenericModuleError;

    /**
     * An error from the underlying `Currency`.
     **/
    CurrencyError: GenericModuleError;
  };
  broker: {
    /**
     * The given region identity is not known.
     **/
    UnknownRegion: GenericModuleError;

    /**
     * The owner of the region is not the origin.
     **/
    NotOwner: GenericModuleError;

    /**
     * The pivot point of the partition at or after the end of the region.
     **/
    PivotTooLate: GenericModuleError;

    /**
     * The pivot point of the partition at the beginning of the region.
     **/
    PivotTooEarly: GenericModuleError;

    /**
     * The pivot mask for the interlacing is not contained within the region's interlace mask.
     **/
    ExteriorPivot: GenericModuleError;

    /**
     * The pivot mask for the interlacing is void (and therefore unschedulable).
     **/
    VoidPivot: GenericModuleError;

    /**
     * The pivot mask for the interlacing is complete (and therefore not a strict subset).
     **/
    CompletePivot: GenericModuleError;

    /**
     * The workplan of the pallet's state is invalid. This indicates a state corruption.
     **/
    CorruptWorkplan: GenericModuleError;

    /**
     * There is no sale happening currently.
     **/
    NoSales: GenericModuleError;

    /**
     * The price limit is exceeded.
     **/
    Overpriced: GenericModuleError;

    /**
     * There are no cores available.
     **/
    Unavailable: GenericModuleError;

    /**
     * The sale limit has been reached.
     **/
    SoldOut: GenericModuleError;

    /**
     * The renewal operation is not valid at the current time (it may become valid in the next
     * sale).
     **/
    WrongTime: GenericModuleError;

    /**
     * Invalid attempt to renew.
     **/
    NotAllowed: GenericModuleError;

    /**
     * This pallet has not yet been initialized.
     **/
    Uninitialized: GenericModuleError;

    /**
     * The purchase cannot happen yet as the sale period is yet to begin.
     **/
    TooEarly: GenericModuleError;

    /**
     * There is no work to be done.
     **/
    NothingToDo: GenericModuleError;

    /**
     * The maximum amount of reservations has already been reached.
     **/
    TooManyReservations: GenericModuleError;

    /**
     * The maximum amount of leases has already been reached.
     **/
    TooManyLeases: GenericModuleError;

    /**
     * The revenue for the Instantaneous Core Sales of this period is not (yet) known and thus
     * this operation cannot proceed.
     **/
    UnknownRevenue: GenericModuleError;

    /**
     * The identified contribution to the Instantaneous Core Pool is unknown.
     **/
    UnknownContribution: GenericModuleError;

    /**
     * The workload assigned for renewal is incomplete. This is unexpected and indicates a
     * logic error.
     **/
    IncompleteAssignment: GenericModuleError;

    /**
     * An item cannot be dropped because it is still valid.
     **/
    StillValid: GenericModuleError;

    /**
     * The history item does not exist.
     **/
    NoHistory: GenericModuleError;

    /**
     * No reservation of the given index exists.
     **/
    UnknownReservation: GenericModuleError;

    /**
     * The renewal record cannot be found.
     **/
    UnknownRenewal: GenericModuleError;

    /**
     * The lease expiry time has already passed.
     **/
    AlreadyExpired: GenericModuleError;

    /**
     * The configuration could not be applied because it is invalid.
     **/
    InvalidConfig: GenericModuleError;
  };
}
