// Generated by dedot cli

import type {
  ConstructorTxOptions,
  SolGenericConstructorTx,
  SolGenericConstructorTxCall,
  SolGenericContractApi,
  SolGenericInstantiateSubmittableExtrinsic,
} from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';
import type { NameInput, SymbolInput } from './types.js';

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends SolGenericContractApi = SolGenericContractApi,
> extends SolGenericConstructorTx<ChainApi> {
  /**
   * @param {bigint} supply
   * @param {NameInput} name
   * @param {SymbolInput} symbol
   * @param {number} decimals
   * @param {ConstructorTxOptions} options
   **/
  initialize: SolGenericConstructorTxCall<
    ChainApi,
    (
      supply: bigint,
      name: NameInput,
      symbol: SymbolInput,
      decimals: number,
      options: ConstructorTxOptions,
    ) => SolGenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>
  >;
}
