// Generated by dedot cli

import type { H160 } from 'dedot/codecs';
import type { GenericContractEvent, GenericContractEvents, MetadataType } from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';
import type { TransferFromInput, TransferToInput } from './types.js';

export interface ContractEvents<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractEvents<ChainApi, Type> {
  Approval: GenericContractEvent<
    'Approval',
    {
      /**
       * @indexed: true
       **/
      owner: H160;
      /**
       * @indexed: true
       **/
      spender: H160;
      /**
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  Transfer: GenericContractEvent<
    'Transfer',
    {
      /**
       * @indexed: true
       **/
      from: TransferFromInput;
      /**
       * @indexed: true
       **/
      to: TransferToInput;
      /**
       * @indexed: false
       **/
      value: bigint;
    },
    Type
  >;
}
