// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type NameInput = [boolean, string];

export type SymbolInput = [boolean, string];

export type TokenNameOutput = [boolean, string];

export type TokenSymbolOutput = [boolean, string];

export type TransferFromInput = [boolean, H160];

export type TransferToInput = [boolean, H160];
