// Generated by dedot cli
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import type { Flipper, InkPrimitivesLangError } from './types.js';

export * from './types.js';

/**
 * @name: FlipperContractApi
 * @contractName: flipper
 * @contractVersion: 5.0.0
 * @authors: Parity Technologies <admin@parity.io>
 * @language: ink! 5.0.0
 **/
export interface FlipperContractApi<ChainApi extends GenericSubstrateApi = SubstrateApi>
  extends InkGenericContractApi<ChainApi> {
  query: ContractQuery<ChainApi>;
  tx: ContractTx<ChainApi>;
  constructorQuery: ConstructorQuery<ChainApi>;
  constructorTx: ConstructorTx<ChainApi, FlipperContractApi>;
  events: ContractEvents<ChainApi>;
  storage: {
    root(): Promise<Flipper>;
    lazy(): WithLazyStorage<Flipper>;
  };

  types: {
    RootStorage: Flipper;
    LazyStorage: WithLazyStorage<Flipper>;
    LangError: InkPrimitivesLangError;
    ChainApi: ChainApi;
  };
}
