name: E2E Contracts API Tests

on:
  push:
  workflow_dispatch:
  merge_group:

jobs:
  zombienet-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - name: Download executables
        run: |
          curl -L -O https://github.com/paritytech/substrate-contracts-node/releases/download/v0.42.0/substrate-contracts-node-linux.tar.gz 
          tar -xzf substrate-contracts-node-linux.tar.gz
          mv ./substrate-contracts-node/substrate-contracts-node ./substrate-contracts-node
          chmod +x substrate-contracts-node

          curl -L -O https://github.com/use-ink/ink-node/releases/download/v0.43.2/ink-node-linux.tar.gz
          tar -xzf ink-node-linux.tar.gz
          mv ./ink-node-linux/ink-node ./ink-node
          chmod +x ink-node

      - name: Spawn networks
        run: |
          export PATH=$(pwd):$PATH
          export RUST_BACKTRACE=full
          ./ink-node --rpc-port=9955 & 
          ./substrate-contracts-node --dev --rpc-port=9944 &

          chmod +x ./e2e/contracts/wait-for-port.sh
          ./e2e/contracts/wait-for-port.sh 9944 30
          ./e2e/contracts/wait-for-port.sh 9955 30

      - name: Run tests
        run: yarn workspace e2e-contracts run e2e:test
