// Generated by @delightfuldot/codegen

import type { GenericChainErrors, GenericModuleError } from '@delightfuldot/types';

export interface ChainErrors extends GenericChainErrors {
  system: {
    /**
     * The name of specification does not match between the current runtime
     * and the new runtime.
     **/
    InvalidSpecName: GenericModuleError;

    /**
     * The specification version is not allowed to decrease between the current runtime
     * and the new runtime.
     **/
    SpecVersionNeedsToIncrease: GenericModuleError;

    /**
     * Failed to extract the runtime version from the new runtime.
     *
     * Either calling `Core_version` or decoding `RuntimeVersion` failed.
     **/
    FailedToExtractRuntimeVersion: GenericModuleError;

    /**
     * Suicide called when the account has non-default composite data.
     **/
    NonDefaultComposite: GenericModuleError;

    /**
     * There is a non-zero reference count preventing the account from being purged.
     **/
    NonZeroRefCount: GenericModuleError;

    /**
     * The origin filter prevent the call to be dispatched.
     **/
    CallFiltered: GenericModuleError;
  };
  utility: {
    /**
     * Too many calls batched.
     **/
    TooManyCalls: GenericModuleError;
  };
  identity: {
    /**
     * Too many subs-accounts.
     **/
    TooManySubAccounts: GenericModuleError;

    /**
     * Account isn't found.
     **/
    NotFound: GenericModuleError;

    /**
     * Account isn't named.
     **/
    NotNamed: GenericModuleError;

    /**
     * Empty index.
     **/
    EmptyIndex: GenericModuleError;

    /**
     * Fee is changed.
     **/
    FeeChanged: GenericModuleError;

    /**
     * No identity found.
     **/
    NoIdentity: GenericModuleError;

    /**
     * Sticky judgement.
     **/
    StickyJudgement: GenericModuleError;

    /**
     * Judgement given.
     **/
    JudgementGiven: GenericModuleError;

    /**
     * Invalid judgement.
     **/
    InvalidJudgement: GenericModuleError;

    /**
     * The index is invalid.
     **/
    InvalidIndex: GenericModuleError;

    /**
     * The target is invalid.
     **/
    InvalidTarget: GenericModuleError;

    /**
     * Too many additional fields.
     **/
    TooManyFields: GenericModuleError;

    /**
     * Maximum amount of registrars reached. Cannot add any more.
     **/
    TooManyRegistrars: GenericModuleError;

    /**
     * Account ID is already named.
     **/
    AlreadyClaimed: GenericModuleError;

    /**
     * Sender is not a sub-account.
     **/
    NotSub: GenericModuleError;

    /**
     * Sub-account isn't owned by sender.
     **/
    NotOwned: GenericModuleError;

    /**
     * The provided judgement was for a different identity.
     **/
    JudgementForDifferentIdentity: GenericModuleError;

    /**
     * Error that occurs when there is an issue paying for judgement.
     **/
    JudgementPaymentFailed: GenericModuleError;
  };
  multisig: {
    /**
     * Threshold must be 2 or greater.
     **/
    MinimumThreshold: GenericModuleError;

    /**
     * Call is already approved by this signatory.
     **/
    AlreadyApproved: GenericModuleError;

    /**
     * Call doesn't need any (more) approvals.
     **/
    NoApprovalsNeeded: GenericModuleError;

    /**
     * There are too few signatories in the list.
     **/
    TooFewSignatories: GenericModuleError;

    /**
     * There are too many signatories in the list.
     **/
    TooManySignatories: GenericModuleError;

    /**
     * The signatories were provided out of order; they should be ordered.
     **/
    SignatoriesOutOfOrder: GenericModuleError;

    /**
     * The sender was contained in the other signatories; it shouldn't be.
     **/
    SenderInSignatories: GenericModuleError;

    /**
     * Multisig operation not found when attempting to cancel.
     **/
    NotFound: GenericModuleError;

    /**
     * Only the account that originally created the multisig is able to cancel it.
     **/
    NotOwner: GenericModuleError;

    /**
     * No timepoint was given, yet the multisig operation is already underway.
     **/
    NoTimepoint: GenericModuleError;

    /**
     * A different timepoint was given to the multisig operation that is underway.
     **/
    WrongTimepoint: GenericModuleError;

    /**
     * A timepoint was given, yet no multisig operation is underway.
     **/
    UnexpectedTimepoint: GenericModuleError;

    /**
     * The maximum weight information provided was too low.
     **/
    MaxWeightTooLow: GenericModuleError;

    /**
     * The data to be stored is already stored.
     **/
    AlreadyStored: GenericModuleError;
  };
  proxy: {
    /**
     * There are too many proxies registered or too many announcements pending.
     **/
    TooMany: GenericModuleError;

    /**
     * Proxy registration not found.
     **/
    NotFound: GenericModuleError;

    /**
     * Sender is not a proxy of the account to be proxied.
     **/
    NotProxy: GenericModuleError;

    /**
     * A call which is incompatible with the proxy type's filter was attempted.
     **/
    Unproxyable: GenericModuleError;

    /**
     * Account is already a proxy.
     **/
    Duplicate: GenericModuleError;

    /**
     * Call may not be made by proxy because it may escalate its privileges.
     **/
    NoPermission: GenericModuleError;

    /**
     * Announcement, if made at all, was made too recently.
     **/
    Unannounced: GenericModuleError;

    /**
     * Cannot add self as proxy.
     **/
    NoSelfProxy: GenericModuleError;
  };
  parachainSystem: {
    /**
     * Attempt to upgrade validation function while existing upgrade pending.
     **/
    OverlappingUpgrades: GenericModuleError;

    /**
     * Polkadot currently prohibits this parachain from upgrading its validation function.
     **/
    ProhibitedByPolkadot: GenericModuleError;

    /**
     * The supplied validation function has compiled into a blob larger than Polkadot is
     * willing to run.
     **/
    TooBig: GenericModuleError;

    /**
     * The inherent which supplies the validation data did not run this block.
     **/
    ValidationDataNotAvailable: GenericModuleError;

    /**
     * The inherent which supplies the host configuration did not run this block.
     **/
    HostConfigurationNotAvailable: GenericModuleError;

    /**
     * No validation function upgrade is currently scheduled.
     **/
    NotScheduled: GenericModuleError;

    /**
     * No code upgrade has been authorized.
     **/
    NothingAuthorized: GenericModuleError;

    /**
     * The given code upgrade has not been authorized.
     **/
    Unauthorized: GenericModuleError;
  };
  balances: {
    /**
     * Vesting balance too high to send value.
     **/
    VestingBalance: GenericModuleError;

    /**
     * Account liquidity restrictions prevent withdrawal.
     **/
    LiquidityRestrictions: GenericModuleError;

    /**
     * Balance too low to send value.
     **/
    InsufficientBalance: GenericModuleError;

    /**
     * Value too low to create account due to existential deposit.
     **/
    ExistentialDeposit: GenericModuleError;

    /**
     * Transfer/payment would kill account.
     **/
    Expendability: GenericModuleError;

    /**
     * A vesting schedule already exists for this account.
     **/
    ExistingVestingSchedule: GenericModuleError;

    /**
     * Beneficiary account must pre-exist.
     **/
    DeadAccount: GenericModuleError;

    /**
     * Number of named reserves exceed `MaxReserves`.
     **/
    TooManyReserves: GenericModuleError;

    /**
     * Number of holds exceed `MaxHolds`.
     **/
    TooManyHolds: GenericModuleError;

    /**
     * Number of freezes exceed `MaxFreezes`.
     **/
    TooManyFreezes: GenericModuleError;
  };
  vesting: {
    /**
     * The account given is not vesting.
     **/
    NotVesting: GenericModuleError;

    /**
     * The account already has `MaxVestingSchedules` count of schedules and thus
     * cannot add another one. Consider merging existing schedules in order to add another.
     **/
    AtMaxVestingSchedules: GenericModuleError;

    /**
     * Amount being transferred is too low to create a vesting schedule.
     **/
    AmountLow: GenericModuleError;

    /**
     * An index was out of bounds of the vesting schedules.
     **/
    ScheduleIndexOutOfBounds: GenericModuleError;

    /**
     * Failed to create a new schedule because some parameter was invalid.
     **/
    InvalidScheduleParams: GenericModuleError;
  };
  dappsStaking: {
    /**
     * Disabled
     **/
    Disabled: GenericModuleError;

    /**
     * No change in maintenance mode
     **/
    NoMaintenanceModeChange: GenericModuleError;

    /**
     * Upgrade is too heavy, reduce the weight parameter.
     **/
    UpgradeTooHeavy: GenericModuleError;

    /**
     * Can not stake with zero value.
     **/
    StakingWithNoValue: GenericModuleError;

    /**
     * Can not stake with value less than minimum staking value
     **/
    InsufficientValue: GenericModuleError;

    /**
     * Number of stakers per contract exceeded.
     **/
    MaxNumberOfStakersExceeded: GenericModuleError;

    /**
     * Targets must be operated contracts
     **/
    NotOperatedContract: GenericModuleError;

    /**
     * Contract isn't staked.
     **/
    NotStakedContract: GenericModuleError;

    /**
     * Contract isn't unregistered.
     **/
    NotUnregisteredContract: GenericModuleError;

    /**
     * Unclaimed rewards should be claimed before withdrawing stake.
     **/
    UnclaimedRewardsRemaining: GenericModuleError;

    /**
     * Unstaking a contract with zero value
     **/
    UnstakingWithNoValue: GenericModuleError;

    /**
     * There are no previously unbonded funds that can be unstaked and withdrawn.
     **/
    NothingToWithdraw: GenericModuleError;

    /**
     * The contract is already registered by other account
     **/
    AlreadyRegisteredContract: GenericModuleError;

    /**
     * This account was already used to register contract
     **/
    AlreadyUsedDeveloperAccount: GenericModuleError;

    /**
     * Smart contract not owned by the account id.
     **/
    NotOwnedContract: GenericModuleError;

    /**
     * Report issue on github if this is ever emitted
     **/
    UnknownEraReward: GenericModuleError;

    /**
     * Report issue on github if this is ever emitted
     **/
    UnexpectedStakeInfoEra: GenericModuleError;

    /**
     * Contract has too many unlocking chunks. Withdraw the existing chunks if possible
     * or wait for current chunks to complete unlocking process to withdraw them.
     **/
    TooManyUnlockingChunks: GenericModuleError;

    /**
     * Contract already claimed in this era and reward is distributed
     **/
    AlreadyClaimedInThisEra: GenericModuleError;

    /**
     * Era parameter is out of bounds
     **/
    EraOutOfBounds: GenericModuleError;

    /**
     * Too many active `EraStake` values for (staker, contract) pairing.
     * Claim existing rewards to fix this problem.
     **/
    TooManyEraStakeValues: GenericModuleError;

    /**
     * Account is not actively staking
     **/
    NotActiveStaker: GenericModuleError;

    /**
     * Transfering nomination to the same contract
     **/
    NominationTransferToSameContract: GenericModuleError;
  };
  blockReward: {
    /**
     * Sum of all rations must be one whole (100%)
     **/
    InvalidDistributionConfiguration: GenericModuleError;
  };
  assets: {
    /**
     * Account balance must be greater than or equal to the transfer amount.
     **/
    BalanceLow: GenericModuleError;

    /**
     * The account to alter does not exist.
     **/
    NoAccount: GenericModuleError;

    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericModuleError;

    /**
     * The given asset ID is unknown.
     **/
    Unknown: GenericModuleError;

    /**
     * The origin account is frozen.
     **/
    Frozen: GenericModuleError;

    /**
     * The asset ID is already taken.
     **/
    InUse: GenericModuleError;

    /**
     * Invalid witness data given.
     **/
    BadWitness: GenericModuleError;

    /**
     * Minimum balance should be non-zero.
     **/
    MinBalanceZero: GenericModuleError;

    /**
     * Unable to increment the consumer reference counters on the account. Either no provider
     * reference exists to allow a non-zero balance of a non-self-sufficient asset, or one
     * fewer then the maximum number of consumers has been reached.
     **/
    UnavailableConsumer: GenericModuleError;

    /**
     * Invalid metadata given.
     **/
    BadMetadata: GenericModuleError;

    /**
     * No approval exists that would allow the transfer.
     **/
    Unapproved: GenericModuleError;

    /**
     * The source account would not survive the transfer and it needs to stay alive.
     **/
    WouldDie: GenericModuleError;

    /**
     * The asset-account already exists.
     **/
    AlreadyExists: GenericModuleError;

    /**
     * The asset-account doesn't have an associated deposit.
     **/
    NoDeposit: GenericModuleError;

    /**
     * The operation would result in funds being burned.
     **/
    WouldBurn: GenericModuleError;

    /**
     * The asset is a live asset and is actively being used. Usually emit for operations such
     * as `start_destroy` which require the asset to be in a destroying state.
     **/
    LiveAsset: GenericModuleError;

    /**
     * The asset is not live, and likely being destroyed.
     **/
    AssetNotLive: GenericModuleError;

    /**
     * The asset status is not the expected status.
     **/
    IncorrectStatus: GenericModuleError;

    /**
     * The asset should be frozen before the given operation.
     **/
    NotFrozen: GenericModuleError;

    /**
     * Callback action resulted in error
     **/
    CallbackFailed: GenericModuleError;
  };
  collatorSelection: {
    /**
     * Too many candidates
     **/
    TooManyCandidates: GenericModuleError;

    /**
     * Too few candidates
     **/
    TooFewCandidates: GenericModuleError;

    /**
     * Unknown error
     **/
    Unknown: GenericModuleError;

    /**
     * Permission issue
     **/
    Permission: GenericModuleError;

    /**
     * User is already a candidate
     **/
    AlreadyCandidate: GenericModuleError;

    /**
     * User is not a candidate
     **/
    NotCandidate: GenericModuleError;

    /**
     * User is already an Invulnerable
     **/
    AlreadyInvulnerable: GenericModuleError;

    /**
     * Account has no associated validator ID
     **/
    NoAssociatedValidatorId: GenericModuleError;

    /**
     * Validator ID is not yet registered
     **/
    ValidatorNotRegistered: GenericModuleError;
  };
  session: {
    /**
     * Invalid ownership proof.
     **/
    InvalidProof: GenericModuleError;

    /**
     * No associated validator ID for account.
     **/
    NoAssociatedValidatorId: GenericModuleError;

    /**
     * Registered duplicate key.
     **/
    DuplicatedKey: GenericModuleError;

    /**
     * No keys are associated with this account.
     **/
    NoKeys: GenericModuleError;

    /**
     * Key setting account is not live, so it's impossible to associate keys.
     **/
    NoAccount: GenericModuleError;
  };
  xcmpQueue: {
    /**
     * Failed to send XCM message.
     **/
    FailedToSend: GenericModuleError;

    /**
     * Bad XCM origin.
     **/
    BadXcmOrigin: GenericModuleError;

    /**
     * Bad XCM data.
     **/
    BadXcm: GenericModuleError;

    /**
     * Bad overweight index.
     **/
    BadOverweightIndex: GenericModuleError;

    /**
     * Provided weight is possibly not enough to execute the message.
     **/
    WeightOverLimit: GenericModuleError;
  };
  polkadotXcm: {
    /**
     * The desired destination was unreachable, generally because there is a no way of routing
     * to it.
     **/
    Unreachable: GenericModuleError;

    /**
     * There was some other issue (i.e. not to do with routing) in sending the message. Perhaps
     * a lack of space for buffering the message.
     **/
    SendFailure: GenericModuleError;

    /**
     * The message execution fails the filter.
     **/
    Filtered: GenericModuleError;

    /**
     * The message's weight could not be determined.
     **/
    UnweighableMessage: GenericModuleError;

    /**
     * The destination `MultiLocation` provided cannot be inverted.
     **/
    DestinationNotInvertible: GenericModuleError;

    /**
     * The assets to be sent are empty.
     **/
    Empty: GenericModuleError;

    /**
     * Could not re-anchor the assets to declare the fees for the destination chain.
     **/
    CannotReanchor: GenericModuleError;

    /**
     * Too many assets have been attempted for transfer.
     **/
    TooManyAssets: GenericModuleError;

    /**
     * Origin is invalid for sending.
     **/
    InvalidOrigin: GenericModuleError;

    /**
     * The version of the `Versioned` value used is not able to be interpreted.
     **/
    BadVersion: GenericModuleError;

    /**
     * The given location could not be used (e.g. because it cannot be expressed in the
     * desired version of XCM).
     **/
    BadLocation: GenericModuleError;

    /**
     * The referenced subscription could not be found.
     **/
    NoSubscription: GenericModuleError;

    /**
     * The location is invalid since it already has a subscription from us.
     **/
    AlreadySubscribed: GenericModuleError;

    /**
     * Invalid asset for the operation.
     **/
    InvalidAsset: GenericModuleError;

    /**
     * The owner does not own (all) of the asset that they wish to do the operation on.
     **/
    LowBalance: GenericModuleError;

    /**
     * The asset owner has too many locks on the asset.
     **/
    TooManyLocks: GenericModuleError;

    /**
     * The given account is not an identifiable sovereign account for any location.
     **/
    AccountNotSovereign: GenericModuleError;

    /**
     * The operation required fees to be paid which the initiator could not meet.
     **/
    FeesNotMet: GenericModuleError;

    /**
     * A remote lock with the corresponding data could not be found.
     **/
    LockNotFound: GenericModuleError;

    /**
     * The unlock operation cannot succeed because there are still consumers of the lock.
     **/
    InUse: GenericModuleError;
  };
  cumulusXcm: {};
  dmpQueue: {
    /**
     * The message index given is unknown.
     **/
    Unknown: GenericModuleError;

    /**
     * The amount of weight given is possibly not enough for executing the message.
     **/
    OverLimit: GenericModuleError;
  };
  xcAssetConfig: {
    /**
     * Asset is already registered.
     **/
    AssetAlreadyRegistered: GenericModuleError;

    /**
     * Asset does not exist (hasn't been registered).
     **/
    AssetDoesNotExist: GenericModuleError;

    /**
     * Failed to convert to latest versioned MultiLocation
     **/
    MultiLocationNotSupported: GenericModuleError;
  };
  xTokens: {
    /**
     * Asset has no reserve location.
     **/
    AssetHasNoReserve: GenericModuleError;

    /**
     * Not cross-chain transfer.
     **/
    NotCrossChainTransfer: GenericModuleError;

    /**
     * Invalid transfer destination.
     **/
    InvalidDest: GenericModuleError;

    /**
     * Currency is not cross-chain transferable.
     **/
    NotCrossChainTransferableCurrency: GenericModuleError;

    /**
     * The message's weight could not be determined.
     **/
    UnweighableMessage: GenericModuleError;

    /**
     * XCM execution failed.
     **/
    XcmExecutionFailed: GenericModuleError;

    /**
     * Could not re-anchor the assets to declare the fees for the
     * destination chain.
     **/
    CannotReanchor: GenericModuleError;

    /**
     * Could not get ancestry of asset reserve location.
     **/
    InvalidAncestry: GenericModuleError;

    /**
     * The MultiAsset is invalid.
     **/
    InvalidAsset: GenericModuleError;

    /**
     * The destination `MultiLocation` provided cannot be inverted.
     **/
    DestinationNotInvertible: GenericModuleError;

    /**
     * The version of the `Versioned` value used is not able to be
     * interpreted.
     **/
    BadVersion: GenericModuleError;

    /**
     * We tried sending distinct asset and fee but they have different
     * reserve chains.
     **/
    DistinctReserveForAssetAndFee: GenericModuleError;

    /**
     * The fee is zero.
     **/
    ZeroFee: GenericModuleError;

    /**
     * The transfering asset amount is zero.
     **/
    ZeroAmount: GenericModuleError;

    /**
     * The number of assets to be sent is over the maximum.
     **/
    TooManyAssetsBeingSent: GenericModuleError;

    /**
     * The specified index does not exist in a MultiAssets struct.
     **/
    AssetIndexNonExistent: GenericModuleError;

    /**
     * Fee is not enough.
     **/
    FeeNotEnough: GenericModuleError;

    /**
     * Not supported MultiLocation
     **/
    NotSupportedMultiLocation: GenericModuleError;

    /**
     * MinXcmFee not registered for certain reserve location
     **/
    MinXcmFeeNotDefined: GenericModuleError;
  };
  evm: {
    /**
     * Not enough balance to perform action
     **/
    BalanceLow: GenericModuleError;

    /**
     * Calculating total fee overflowed
     **/
    FeeOverflow: GenericModuleError;

    /**
     * Calculating total payment overflowed
     **/
    PaymentOverflow: GenericModuleError;

    /**
     * Withdraw fee failed
     **/
    WithdrawFailed: GenericModuleError;

    /**
     * Gas price is too low.
     **/
    GasPriceTooLow: GenericModuleError;

    /**
     * Nonce is invalid
     **/
    InvalidNonce: GenericModuleError;

    /**
     * Gas limit is too low.
     **/
    GasLimitTooLow: GenericModuleError;

    /**
     * Gas limit is too high.
     **/
    GasLimitTooHigh: GenericModuleError;

    /**
     * Undefined error.
     **/
    Undefined: GenericModuleError;

    /**
     * EVM reentrancy
     **/
    Reentrancy: GenericModuleError;

    /**
     * EIP-3607,
     **/
    TransactionMustComeFromEOA: GenericModuleError;
  };
  ethereum: {
    /**
     * Signature is invalid.
     **/
    InvalidSignature: GenericModuleError;

    /**
     * Pre-log is present, therefore transact is not allowed.
     **/
    PreLogExists: GenericModuleError;
  };
  dynamicEvmBaseFee: {
    /**
     * Specified value is outside of the allowed range.
     **/
    ValueOutOfBounds: GenericModuleError;
  };
  contracts: {
    /**
     * A new schedule must have a greater version than the current one.
     **/
    InvalidScheduleVersion: GenericModuleError;

    /**
     * Invalid combination of flags supplied to `seal_call` or `seal_delegate_call`.
     **/
    InvalidCallFlags: GenericModuleError;

    /**
     * The executed contract exhausted its gas limit.
     **/
    OutOfGas: GenericModuleError;

    /**
     * The output buffer supplied to a contract API call was too small.
     **/
    OutputBufferTooSmall: GenericModuleError;

    /**
     * Performing the requested transfer failed. Probably because there isn't enough
     * free balance in the sender's account.
     **/
    TransferFailed: GenericModuleError;

    /**
     * Performing a call was denied because the calling depth reached the limit
     * of what is specified in the schedule.
     **/
    MaxCallDepthReached: GenericModuleError;

    /**
     * No contract was found at the specified address.
     **/
    ContractNotFound: GenericModuleError;

    /**
     * The code supplied to `instantiate_with_code` exceeds the limit specified in the
     * current schedule.
     **/
    CodeTooLarge: GenericModuleError;

    /**
     * No code could be found at the supplied code hash.
     **/
    CodeNotFound: GenericModuleError;

    /**
     * A buffer outside of sandbox memory was passed to a contract API function.
     **/
    OutOfBounds: GenericModuleError;

    /**
     * Input passed to a contract API function failed to decode as expected type.
     **/
    DecodingFailed: GenericModuleError;

    /**
     * Contract trapped during execution.
     **/
    ContractTrapped: GenericModuleError;

    /**
     * The size defined in `T::MaxValueSize` was exceeded.
     **/
    ValueTooLarge: GenericModuleError;

    /**
     * Termination of a contract is not allowed while the contract is already
     * on the call stack. Can be triggered by `seal_terminate`.
     **/
    TerminatedWhileReentrant: GenericModuleError;

    /**
     * `seal_call` forwarded this contracts input. It therefore is no longer available.
     **/
    InputForwarded: GenericModuleError;

    /**
     * The subject passed to `seal_random` exceeds the limit.
     **/
    RandomSubjectTooLong: GenericModuleError;

    /**
     * The amount of topics passed to `seal_deposit_events` exceeds the limit.
     **/
    TooManyTopics: GenericModuleError;

    /**
     * The chain does not provide a chain extension. Calling the chain extension results
     * in this error. Note that this usually shouldn't happen as deploying such contracts
     * is rejected.
     **/
    NoChainExtension: GenericModuleError;

    /**
     * A contract with the same AccountId already exists.
     **/
    DuplicateContract: GenericModuleError;

    /**
     * A contract self destructed in its constructor.
     *
     * This can be triggered by a call to `seal_terminate`.
     **/
    TerminatedInConstructor: GenericModuleError;

    /**
     * A call tried to invoke a contract that is flagged as non-reentrant.
     * The only other cause is that a call from a contract into the runtime tried to call back
     * into `pallet-contracts`. This would make the whole pallet reentrant with regard to
     * contract code execution which is not supported.
     **/
    ReentranceDenied: GenericModuleError;

    /**
     * Origin doesn't have enough balance to pay the required storage deposits.
     **/
    StorageDepositNotEnoughFunds: GenericModuleError;

    /**
     * More storage was created than allowed by the storage deposit limit.
     **/
    StorageDepositLimitExhausted: GenericModuleError;

    /**
     * Code removal was denied because the code is still in use by at least one contract.
     **/
    CodeInUse: GenericModuleError;

    /**
     * The contract ran to completion but decided to revert its storage changes.
     * Please note that this error is only returned from extrinsics. When called directly
     * or via RPC an `Ok` will be returned. In this case the caller needs to inspect the flags
     * to determine whether a reversion has taken place.
     **/
    ContractReverted: GenericModuleError;

    /**
     * The contract's code was found to be invalid during validation or instrumentation.
     *
     * The most likely cause of this is that an API was used which is not supported by the
     * node. This happens if an older node is used with a new version of ink!. Try updating
     * your node to the newest available version.
     *
     * A more detailed error can be found on the node console if debug messages are enabled
     * by supplying `-lruntime::contracts=debug`.
     **/
    CodeRejected: GenericModuleError;

    /**
     * An indetermistic code was used in a context where this is not permitted.
     **/
    Indeterministic: GenericModuleError;

    /**
     * A pending migration needs to complete before the extrinsic can be called.
     **/
    MigrationInProgress: GenericModuleError;

    /**
     * Migrate dispatch call was attempted but no migration was performed.
     **/
    NoMigrationPerformed: GenericModuleError;
  };
  sudo: {
    /**
     * Sender must be the Sudo account
     **/
    RequireSudo: GenericModuleError;
  };
}
